### ISSUE TITLE
Error while adding azure CLI extension 'az extension add --name azure-devops'

### ISSUE THREAD

**Issue by bss20** [Azure/azure-devops-cli-extension#1017]
I have installed Azure CLI but facing issue while adding azure devops extension.
Unable to get extension index.
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /azure-cli-extension-index-v1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x060F1430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Please provide solution.
Thank you.

**Comment by mmigala** [comment]
any updates on this issue ?

**Comment by bss20** [comment]
The issue was related to proxy, either we can set proxy variable as permanent solution or use set proxy command.
