### ISSUE TITLE
get user list sorted by lastAccessedDate in Az devops 

### ISSUE THREAD

**Issue by ankita11194** [Azure/azure-devops-cli-extension#1019]
![Capture](https://user-images.githubusercontent.com/66828526/84896003-cc899700-b0c0-11ea-9496-f055f0b4d1ff.PNG)

Not able to get user list in tabular format, as column1 : name, column1 : date

can anyone help?

**Comment by smunj** [comment]
Using JMES query, you can run the command 
az devops user list --query ["members[].[user.displayName, lastAccessedDate]"]
But this will not give the required solution to your problem. 

In case you want a tabular format, you can use PS scripting for an easier implementation
$d = az devops user list | ConvertFrom-Json | Select-Object Expand-Members
$e = $d | Select @{Name="Name";E={$_.user | Select -Expand displayName}}, LastAccessedDate
$e | Sort-Object -Property  lastAccessedDate, Name

Will give the required table sorted on last Accessed Date

I hope this resolves your issue

**Comment by ankita11194** [comment]
Hi ,

I did the same yesterday and it helped.
But now stuck while integrating it with powershell as I want to mail  the
list of users.
Can you help?


Thank,
Ankita Agrawal

**Comment by smunj** [comment]
What exactly do you mean by integrating with powershell? Can you be more specific as to what exactly do you need help with, maybe attach some screenshot if there is some error, or explain what you are trying to do.

Thanks

**Comment by ankita11194** [comment]
I am trying to get users from azure cli  devops extension and I want those
users monthly .. I need to schedule it as task or something and mail the
result to the team.
Hence I need to integrate it with powershell so I can run enter-pssession
and schedule a task n mail the result. Is something possible here?

**Comment by ashishonce** [comment]
@ankita11194 closing this issue as has been stale for long. 
Please feel free to open is again , in-case required.
