### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by quasarea** [Azure/azure-devops-cli-extension#1057]
**Describe the bug**
Following "Get the tools" manual on https://dev.azure.com connect to feed for universal packages
Installed Azure CLI 2.12.1
Executing 
```
az extension add --name azure-devops
```
leads to:
```
ValidationError: An error occurred. Pip failed with status code 1. Use --debug for more information.
```
using --debug:
```
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /s/files.pythonhosted.org/packages/fa/f5/9e315fe8cb985b0ce052b34bcb767883dc739f46fadb62f05a7e6d6eedbe/msrest-0.6.19-py2.py3-none-any.whl?X-OpenDNS-Session=_5a804d1f0658404e01091220e9ba0a08acdb9270fc52_z5JN3SA9_
  Starting new HTTPS connection (6): files.pythonhosted.org.x.5a804d1f0658404e01091220e9ba0a08acdb.9270fc52.id.opendns.com:443
```
full log attached

**To Reproduce**
Azure Cli Version: 2.12.1

Azure-Devops extension version: 
azure_devops-0.18.0-py2.py3-none-any.whl (thats what its trying to install

1. no login required
2. just install latest cli on clean machine and try to install extension
3. I was able to replicate it on 4 different windows 10.1803 machines 

**Expected behavior**
Getting package installed

**Debug logs**
Attached

[azure-devops.log](https://github.com/Azure/azure-devops-cli-extension/files/5340381/azure-devops.log)

**Comment by PatrickHutch** [comment]
Same issue here as well.

**Comment by stuartjsmith** [comment]
I also see this issue, cannot figure out how to resolve or how to fix my environment

**Comment by quasarea** [comment]
fixed by perl certification
