### ISSUE TITLE
[Bug] az devops security group create fails with "API resource location … is not registered on …"

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devops-cli-extension#1105]
**Describe the bug**
When running any `az devops security group *` command against Azure DevOps Server 2020 (e.g. `az devops security group create` or `list`) it fails with the error message:

> API resource location 048aee0a-7072-4cde-ab73-7af77b1e0b4e is not registered <Collection_URL>

**To Reproduce**

**Versions:**
azure-cli 2.19.1
azure-devops: 0.18.0
Azure DevOps Server: 2020.RTW

1. Set PAT to `AZURE_DEVOPS_EXT_PAT` environment variable
2. Run command: `az devops project list --org http://server:8080/tfs/collection` runs **fine**
3. Run command: `az devops security group list --org http://server:8080/tfs/collection --scope organization` **fails**

**Expected behavior**
It should list the security groups.

**Screenshots**
![bug-azdevopsext-group](https://user-images.githubusercontent.com/13981145/108105940-8fc9d180-708d-11eb-9eda-405826ede847.png)

**Debug logs**
Available upon request (contains private URLs)

**Comment by junior2200** [comment]
I am exactly  facing same issue.
My version: 
"azure-cli": "2.20.0",
  "azure-cli-core": "2.20.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0"
    
Azure DevOps Server Version Dev18.M170.8

**Comment by gauravsaralMs** [comment]
seems like a dup of https://github.com/Azure/azure-devops-cli-extension/issues/666

**Comment by gauravsaralMs** [comment]
@mrweiland agree
however CLI is not supported for both server 2019 or server 2020

**Comment by NenoLoje** [comment]
@mrweiland: That is not entirely correct:

> The Azure DevOps Command Line Interface (CLI) is available for Azure DevOps Server 2020 and Azure DevOps Services.
from: https://docs.microsoft.com/en-us/azure/devops/cli/

**Comment by sunghwan2789** [comment]
These are more commands that fail on Azure DevOps Server Express 2020.0.1 Patch 2:

```
$ az devops user list --org http://127.0.0.1:8080/tfs/defaultcollection
API resource location 387f832c-dbf2-4643-88e9-c1aa94dbb737 is not registered on http://127.0.0.1:8080/tfs/defaultcollection.

$ az devops user show --user bob --org http://127.0.0.1:8080/tfs/defaultcollection
API resource location 8480c6eb-ce60-47e9-88df-eca3c801638b is not registered on http://127.0.0.1:8080/tfs/defaultcollection.

```

**Comment by NenoLoje** [comment]
What we probably need is some documentation which CLI commands are compatible with DevOps Server 2020 and which are not.

**Comment by roshan-sy** [comment]
@NenoLoje 

Looks this Issue is already fixed with https://github.com/Azure/azure-devops-cli-extension/issues/666#issuecomment-502097018

Can you please confirm the same?
So, we can close this bug.

**Comment by NenoLoje** [comment]
@roshan-sy It seems that Azure CLI now prints out that the "CLI is not supported on Azure DevOps Server", which is technically not correct.

According to [the docs](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops&WT.mc_id=DOP-MVP-21138) it is supported, just a few APIs (the ones using the Graph API) are not.

Ideally, we would just mark those APIs and make this clear.

**Comment by roshan-sy** [comment]
@NenoLoje 
Sure, I am creating a separate issue for that, and let's close this one.
