### ISSUE TITLE
Remove dependencies already installed by azure-cli

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-devops-cli-extension#1108]
There are 3 required dependencies in setup.py now:
https://github.com/Azure/azure-devops-cli-extension/blob/2bd72a1d76cc00a84b348f573e9f8e14dfb42c5b/azure-devops/setup.py#L20-L24

`python-dateutil` and `msrest` are also required dependencies by `azure-cli` (check the [requirements file](https://github.com/azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt)). They should be removed as they will slow down the installation of the `azure-devops` extension and they will not be used after installed in the extension directory since modules of the same name installed by `azure-cli` have higher priority when loaded by python.

**Comment by roshan-sy** [comment]
Done
Removed the stated dependency from the code.
