### ISSUE TITLE
[Feature Request] Allow setting remote related WI relations

### ISSUE THREAD

**Issue by asmundg** [Azure/azure-devops-cli-extension#1109]
**Is your feature request related to a problem? Please describe.**
`az boards work-item relation add` has a hard requirement on the added relation being a link to a local work item that can be looked up by id. This means that it's impossible to add a relation to a remote related work item, since this does not have a local work item id that can be looked up.

**Describe the solution you'd like**
It should be possible to add a remote related work item relation. This would mean skipping the required id lookup, which  means adding a new command:

```
az boards work-item relation add-url
```

**Additional context**

**Comment by roshan-sy** [comment]
Proposed solution
Instead of adding a new command, we can add a new parameter `--target-url`.
Cli will conditionally use between `target-url` and `target-id`

**Comment by roshan-sy** [comment]
> Proposed solution Instead of adding a new command, we can add a new parameter `--target-url`. Cli will conditionally use between `target-url` and `target-id`

@asmundg Shall I go ahead with this approach?
