### ISSUE TITLE
Support for paging using az devops invoke when continuation token is in header

### ISSUE THREAD

**Issue by Tiberriver256** [Azure/azure-devops-cli-extension#1112]
Example command:

```sh
az devops invoke --area distributedtask --resource jobrequests --route-parameters poolId={myPoolId} --organization {myOrg} --query-parameters `$top=1
```

will translation to the following URL:

```
{myOrg}/_apis/distributedtask/pools/{myPoolId}/jobrequests?$top=1
```

This works as expected and returns a JSON response to the console. The problem is that, if I need to get to the next page, the server sends the continuation token as a header instead of embedded in the JSON body response and az devops invoke doesn't expose response headers at all, that I can see.

**Comment by roshan-sy** [comment]
Looks like API do not support continuation token.

@Tiberriver256 
Can you please check

**Comment by Tiberriver256** [comment]
Hi roshan, sorry for the confusion. Could you use the build definitions list endpoint as an example?

https://docs.microsoft.com/en-us/rest/api/azure/devops/build/definitions/list?view=azure-devops-rest-6.0

There are several endpoints that use the continuation token in the header as a paging mechanism so I can pick another if you like.

**Comment by roshan-sy** [comment]
Fixed.

Will be available after next release.
