### ISSUE TITLE
[Bug] az pipelines runs list --pipeline-ids does not behave according to documentation

### ISSUE THREAD

**Issue by droopy4096** [Azure/azure-devops-cli-extension#1113]
**Describe the bug**

`az pipelines runs list --pipeline-ids` does **NOT** support multiple entries despite the documentation:

```
IDs (space separated) of definitions to list builds for.
```

**To Reproduce**
Azure CLI versions:
```
{
  "azure-cli": "2.21.0",
  "azure-cli-core": "2.21.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.73",
    "azure-devops": "0.18.0",
    "keyvault-preview": "0.1.3"
  }
}
```

1. login using az login
2. setup defaults..
3. ```
   az pipelines runs list --project fooproj  --pipeline-ids='565 571' > /tmp/foo.json
   ERROR: argument --pipeline-ids: invalid int value: '565 571'
   ```

**Expected behavior**
I should've received list of runs from pipelines `565` and `571`

**Screenshots**
None

**Debug logs**

```
DEBUG: cli.knack.cli: Command arguments: ['pipelines', 'runs', 'list', '--debug', '--project', 'fooproj', '--pipeline-ids=565 571']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f2dc5a079d8>, <function OutputProducer.on_global_arguments at 0x7f2dc5955730>, <function CLIQuery.on_global_arguments at 0x7f2dc58e99d8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'pipelines': ['azext_devops']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: azure-devops              0.021        60       191  /home/dmitrymakovey/.azure/cliextensions/azure-devops
DEBUG: cli.azure.cli.core: Total (1)                 0.021        60       191  
DEBUG: cli.azure.cli.core: Loaded 60 groups, 191 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : pipelines runs list
DEBUG: cli.azure.cli.core: Command table: pipelines run
DEBUG: cli.azure.cli.core: remaining    :                list
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f2dc5553510>]
INFO: az_command_data_logger: command args: pipelines runs list --debug --project {} --pipeline-ids={}
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/dmitrymakovey/.azure/commands'.
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f2dc5505598>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f2dc5462c80>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f2dc5462d08>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f2dc5462e18>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
DEBUG: urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22pipelines+runs+list%22%2C+%22parameters%22%3A+%22--pipeline-ids%2C--project%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.21.0%22%2C+%22errorType%22%3A+%22InvalidParameterValue%22%2C+%22correlationId%22%3A+%22ddc8468d-c3db-414a-b2af-879de1714de4%22%2C+%22subscriptionId%22%3A+%22928a77fe-5eca-48fe-a2fb-b1271a48c266%22%7D HTTP/1.1" 200 None
ERROR: cli.azure.cli.core.azclierror: argument --pipeline-ids: invalid int value: '565 571'
ERROR: cli.azure.cli.core.azclierror: argument --pipeline-ids: invalid int value: '565 571'
```

**Additional context**
None

**Comment by roshan-sy** [comment]
Command works fine when

`az pipelines runs list --project DemoProject --pipeline-ids 1 2`

Updating the example in the document
![image](https://user-images.githubusercontent.com/83656375/126106337-5b794f12-59ab-4c74-8efb-c78bdcd13b0f.png)
