### ISSUE TITLE
[Bug] az repos pr create with providing the same reviewer twice gives a 500, should be accepted or return a 4xx 

### ISSUE THREAD

**Issue by FitzgeraldKrudde** [Azure/azure-devops-cli-extension#1118]
**Describe the bug**
When providing the same reviewer (email) twice the command fails with:
`ClientRequestError: Error occurred in request... Caused by ResponseError('too many 500 error responses')`

**To Reproduce**
Azure Cli Version: 
azure-cli (2.14.0)
Azure-Devops extension version: 
azure-devops (0.18.0)

1. login using az login
2. create a repository
3. Run `az repos pr create --reviewers='UUID1' 'UUID1'` (with some sensible value for UUID1) 

**Expected behavior**
Either that the request is accepted (the reviewers are de-doubled) or a 4xx response indicating the client request is incorrect

**Comment by roshan-sy** [comment]
`reviewers = list(set(x.lower() for x in reviewers))`

Can be used to discrad duplicate reviewers email ids

**Comment by gauravsaralMs** [comment]
@roshan-sy makes sense, are we able to repro this issue?  then we can if it works with the fix

**Comment by roshan-sy** [comment]
> @roshan-sy makes sense, are we able to repro this issue? then we can if it works with the fix

Yes, I am able to reproduce it

Going with above mentioned solution
ETA : Today (20 Sep) EOD
