### ISSUE TITLE
[Feature Request] az repos ref delete make object-id parameter optional

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-devops-cli-extension#1132]
**Describe the solution you'd like**
Please consider making `--object-id` optional parameter and fetch the value for it automatically in `az repos ref delete` command.

**Comment by POLIMATISUNILBABU** [comment]
I find one page with the method --> az repos ref delete

# delete the reference
            delete_command = 'az repos ref delete --name {} --object-id {} {}'.format(REF_NAME, created_object_id, REPO_NAME)
            deleted_ref = self.cmd(delete_command).get_output_in_json()
            assert deleted_ref is not None
            assert created_ref['updateStatus'] == 'succeeded'
            assert created_ref['success'] is True


--> I commented the existing object id parameter
# assert created_object_id is not None
Created new object id like below
 assert created_object_id is None

**Comment by gauravsaralMs** [comment]
@POLIMATISUNILBABU : please explore the working of [az repos ref list](https://docs.microsoft.com/en-us/cli/azure/repos/ref?view=azure-cli-latest#az_repos_ref_list)

for a given ref name we should be able to detect the object id using the logic present in [az repos ref list](https://docs.microsoft.com/en-us/cli/azure/repos/ref?view=azure-cli-latest#az_repos_ref_list)
