### ISSUE TITLE
[Bug] az repos ref create

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-devops-cli-extension#1133]
**Describe the bug**
`az repos ref create` should exit with non zero exit code when it could not complete the action instead of exiting with 0 and showing the error:
```json
{
  "customMessage": "TF401027: You need the Git 'CreateBranch' permission to perform this action. Details: identity '<guid>\\email', scope 'repository'.",
  "isLocked": false,
  "name": "refs/heads/branch1",
  "newObjectId": "05abcd2cfc888fccc25b132bb777d84b84d169a8",
  "oldObjectId": "0000000000000000000000000000000000000000",
  "rejectedBy": null,
  "repositoryId": "<guid>",
  "success": false,
  "updateStatus": "createBranchPermissionRequired"
}
```
**To Reproduce**
Azure Cli Version: 
```
azure-cli                         2.21.0 *

core                              2.21.0 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
```

1. Remove `Create branch` permission for the identity from the repository.
2. Try to create a branch with that identity.

**Expected behavior**
`az` exits with non zero exit code.

**Comment by roshan-sy** [comment]
-  Time taken to come up with proposal and timeline : 0.5 day

### Proposal
We can check if failure reason is 'createBranchPermissionRequired' or 'createTagPermissionRequired'
We can change the status to success
![1133](https://user-images.githubusercontent.com/83656375/129317091-7ba83455-8c7f-4551-91fb-294f0dcdb6cf.png)


## Expected timeline
implementation - 0.5 day - 16 Aug
unit test - 1 day - 17 Aug

**Comment by gauravsaralMs** [comment]
@roshan-sy : thanks for the detailed proposal 😄 

I will suggest to take dependency only on response.success

```python
if response.success is false:
  raise new CLIException(response.message)
``

because I belive the ask from customer is to not return 0 (success) in case operation failed on ADO service side.
