### ISSUE TITLE
[Bug] az boards work-item create --fields does not support multiple fields

### ISSUE THREAD

**Issue by keithbabinec** [Azure/azure-devops-cli-extension#1134]
**Describe the bug**
The ```az boards work-item create``` command parameter ```--fields``` help says: 

> Space separated "field=value" pairs for custom fields you would like to set.

This implies you can submit multiple fields, but this isn't true. You can only submit one field at a time.

**To Reproduce**
Azure Cli Version: v2.24.2
Azure-Devops extension version: v0.18.0

1. Call ```az boards work-item create``` with more than one field-value pair item in ```--fields```. 
2. The command fails with error ```The --fields argument should consist of space separated "field=value" pairs.```

**Expected behavior**
I expect multiple fields to be supported in both ```work-item create``` and ```work-item update```, because this is what the documentation says. Creating/updating many fields creates unnecessary HTTP calls.

**Screenshots**
It looks like the bug can be found on line 83 of [work_item.py](https://github.com/Azure/azure-devops-cli-extension/blob/2bd72a1d76cc00a84b348f573e9f8e14dfb42c5b/azure-devops/azext_devops/dev/boards/work_item.py). There is a line of code that checks the length of the field-value pair arguments (after splitting on '=' characters). if exactly one field-value pair item (length 2) is provided, it succeeds. If any other items are provided the error is thrown. This same bug is present for both ```work-item create``` and ```work-item update```.

![image](https://user-images.githubusercontent.com/9817416/121100217-37d6e800-c7ae-11eb-8445-e5eea490bd0b.png)

**Debug logs**
..

**Additional context**
..

**Comment by gitet** [comment]
I made a quick and dirty work-around for myself while waiting for MS to patch.
Code below expects the --fields argument string to use "," to separate the field key/value pairs: 

       if fields is not None and fields:
            fields = fields[0].split(',')
            for field in fields:
                kvp = field.split('=', 1)
                print(len(patch_document))
                if len(kvp) == 2:
                    patch_document.append(_create_work_item_field_patch_operation('add', kvp[0], kvp[1]))
                else:
                    raise ValueError('The --fields argument should consist of space separated "field=value" pairs.')

**Comment by keithbabinec** [comment]
@gitet -- nice, thanks for coming up with one. I will test this next week when I'm in the office.

**Comment by gauravsaralMs** [comment]
@roshan-sy : can you please help with this?

**Comment by roshan-sy** [comment]
Sure, Checking

**Comment by roshan-sy** [comment]
FYI

Already works fine when the command is
`az boards work-item create --title Test --type Task --project DemoProject --fields "Description=Something important" "Priority=2" "AnotherProp=Some value"`

i.e. Field value pair is enclosed in double quotes.

Does not work when
`az boards work-item create --title Test --type Task --project DemoProject --fields "Description=Something important Priority=2 AnotherProp=Some value"`
OR
`az boards work-item create --title Test --type Task --project DemoProject --fields Description=Something important Priority=2 AnotherProp=Some value`

**Comment by roshan-sy** [comment]
To make it more user friendly, I have added the example in the help text.
