### ISSUE TITLE
add a warning when calls go to Server.

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-devops-cli-extension#1151]
Azure DevOps has 2 offering

- [Azure DevOps service](https://azure.microsoft.com/en-in/services/devops/)
- [Azure DevOps server](https://azure.microsoft.com/en-in/services/devops/server/)

This CLI offering is supported against Azure DevOps service but **not** against Azure DevOps server.
The Goal of this feature is to add a warning message if this CLI is used against Azure DevOps server

**Comment by roshan-sy** [comment]
Added warning 
**Support for Azure DevOps Server, is in preview and under development**
