### ISSUE TITLE
Release version 0.20.0 for ADO CLI

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-devops-cli-extension#1152]
Document to be followed for release:
https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/release_new_version.md 

- [ ] update version to 0.21.0 in code post release. sample PR https://github.com/Azure/azure-devops-cli-extension/pull/1082

**Comment by gauravsaralMs** [comment]
@roshan-sy : Kudos on releasing version 0.20.0
https://github.com/Azure/azure-cli-extensions/pull/3744#pullrequestreview-723922690

please pick up remaining task in the task list to upgrade code to release next version 0.21.0
similar to https://github.com/Azure/azure-devops-cli-extension/pull/1082

**Comment by roshan-sy** [comment]
> @roshan-sy : Kudos on releasing version 0.20.0
> [Azure/azure-cli-extensions#3744 (review)](https://github.com/Azure/azure-cli-extensions/pull/3744#pullrequestreview-723922690)
> 
> please pick up remaining task in the task list to upgrade code to release next version 0.21.0
> similar to #1082

Thanks Gaurav

Yes working on remaining task
