### ISSUE TITLE
Investigate/ fix failures in live tests

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-devops-cli-extension#1165]
https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=205118&view=logs&j=15d4e81f-d43d-597d-0244-b3aa26f78abd

- [x] #1173
- [x] #1174
- [x] #1175
- [x] #1176
- [x] #1177
- [x] #1179
- [x] #1180
- [x] #1181
- [x] #1182

Adding new / remaining issues

- [x] #1192 
- [x] #1193 
- [x] #1194 
- [x] #1195
- [x] #1202

**Comment by roshan-sy** [comment]
Adding new / remaining issues

- [ ] #1192 
- [ ] #1193 
- [ ] #1194 
- [ ] #1195
