### ISSUE TITLE
Not able to download universal packages from public feeds

### ISSUE THREAD

**Issue by freddydk** [Azure/azure-devops-cli-extension#1395]
**Command Name**

`az artifacts universal download --organization https://dev.azure.com/dynamicssmb2 --project DynamicsBCPublicFeeds --scope project --feed bcartifacts --name sandbox.us.21 --version 5.53619.62937`

**Errors:**
```
ERROR: Failed to update Universal Packages tooling.
Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
```

## To Reproduce:
```
az logout
az artifacts universal download --organization https://dev.azure.com/dynamicssmb2 --project DynamicsBCPublicFeeds --scope project --feed bcartifacts --name sandbox.us.21 --version 5.53619.62937
```

We have public feeds for our partners to download packages - they should not need to authenticate to anything in order to download packages from our public feed.
It seems like the upgrade feature is requiring the authentication - not the actual download.

Is there any way I can tell az to not check for updates?

## Expected Behavior

That the public package is downloaded

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.11.5
Installer: MSI

azure-cli 2.56.0

Extensions:
azure-devops 0.26.0

Dependencies:
msal 1.24.0b2
azure-mgmt-resource 23.1.0b2
```

**Comment by jmyersmsft** [comment]
Anonymous access to Universal Packages is not currently supported. Even if you could download the tooling, you wouldn't be able to access the contents of the package. Adding that functionality would require both client and server changes, which are not currently planned.

I agree that we should have that feature, but our backlog is currently full of higher-priority items, sorry.
