### ISSUE TITLE
Feature Request: Add Ability to specify multiple PRs using "vsts code pr --id"

### ISSUE THREAD

**Issue by jetzerb** [Azure/azure-devops-cli-extension#140]
When we prep for a code release, we identify a bunch of PRs to complete, merging into our mainline branch.  I'd like to be able to specify a list of PRs using "vsts code pr" so that I can monitor the state of each of the PRs over time.  Ideally, I'd do something like
  `vsts code pr --id 123,456,789,etc --output table`
and be able to see which PRs are completed and which ones still need attention.

thanks
--Bill

**Comment by thecraftman** [comment]
Wow thanks for this

**Comment by geverghe** [comment]
With the new azure devops extension, wouldn't `az repos pr list` with either the `source` or `target` branch filter work for your use case? This way, you wouldn't have to even remember IDs. Further, in case you really want to explicitly want to filter out IDs from this result set, you could use JMES path query to filter down on the result set.  Let me know if this still does not suffice your requirement.
