### ISSUE TITLE
SSL_Validation in case of multiple not trusted certificates

### ISSUE THREAD

**Issue by cage200** [Azure/azure-devops-cli-extension#220]
Hello,

I have read already the issue #76 but the solution is not working under the corporate network.

In case of Azure Devops multiple links are used and they have different root certificates.How can I add multiple certificates to REQUESTS_CA_BUNDLE ? I tried a Pem file but does not work.

Regards.

**Comment by geverghe** [comment]
@atbagga can you have a look into this?

**Comment by atbagga** [comment]
@cage200 Apologies for no action since a long time on this. Are you still facing this issue with azure-devops extension on Azure Cli?

**Comment by atbagga** [comment]
@cage200 Closing the issue. Please reopen if you still face this issue with the new extension.
