### ISSUE TITLE
Pipelines commands - Create, update, list and run a pipeline; list, show and tag pipeline runs

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-devops-cli-extension#333]
|  Command | Description  	|   	
|---	|---	|	
| az pipelines create   	|   Create a pipeline (both from YAML & a GIT repo) 	|   
| az pipelines  delete 	|   Delete a pipeline |     	
| az pipelines update       |  Open the pipeline YAML in default editor. 	|   
| az pipelines run             |  Run a pipeline manually  	|   
| az pipelines list              |   List all pipelines and their status |   
| az pipelines show          |  Show details pertaining to a pipeline  	|   
| az pipelines runs list |  List of pipeline runs |
| az pipelines runs show |  Show details of a pipeline run |
| az pipelines runs tag add |  Add tags to a pipeline run |
| az pipelines runs tag list |  List tags assigned to a pipeline run|
| az pipelines runs tag delete |  Delete a tag from a pipeline run |

**Comment by jaraco** [comment]
In [this document](https://marketplace.visualstudio.com/items?itemName=ms-vsts.cli), which links to this repo, it suggests that the `vsts build` command is used for working with pipelines... but the set above refers to a different command and subcommand. Where should I be hanging my hopes for a CLI for managing pipelines in dev.azure.com?

**Comment by atbagga** [comment]
@jaraco  Firstly apologies for outdated documentation. We will have it updated soon. 

The [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) with the [Azure DevOps extension](https://github.com/Microsoft/azure-devops-cli-extension) has replaced the VSTS CLI. The VSTS CLI has been deprecated and will no longer be receiving new features. We recommend that users of the VSTS CLI switch to the Azure CLI and add the Azure DevOps extension. To get started refer the quick start guide in the [readme](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/README.md) of this repo. 

The commands which were supported in VSTS-CLI are all available in the Azure DevOps Extension.
So vsts build list is now az pipelines build list and so on. You can checkout the existing pipelines command [here](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest). 

This feature request is to enhance the pipeline commands to support yml based definitions too and letting you create and update pipelines which was not supported in VSTS CLI.   

Let us know if you face any issues in getting started.

**Comment by jaraco** [comment]
That's super helpful. I'm already using the Azure CLI, so happy to see that functionality consolidated. I'll read up on the DevOps extension now. Cheers!

**Comment by geverghe** [comment]
Create pipelines, experience fine-tunings
- [ ] Queue id needs to be auto filled if user does not provide one. Also evaluate recommendation to include queue.
- [x] ~Auto detect of url and branch when working out of local checkout of repo.~
- [x] ~Ensure pipeline is triggered post create.~


New asks:
- [ ] Listing experience for AKS cluster and ACRs when using kubernetes template
- [ ] Listing experience for namespace for selected cluster and ability to create
- [ ] Accommodate additional kubernetes manifest file along with YAML check in.
- [ ] Follow up on authorization issue.
- [ ] Docker file port read should be included in template

@atbagga - FYI

**Comment by GiridharanNarayanan** [comment]
@geverghe , You able to track this?

**Comment by GiridharanNarayanan** [comment]
@geverghe Is it working ?

**Comment by atbagga** [comment]
The pipelines commands mentioned here are available in version 0.7.0 and above. 
Closing the issue.
