### ISSUE TITLE
vsts-cli is deprecated

### ISSUE THREAD

**Issue by mbrancato** [Azure/azure-devops-cli-extension#458]
This is apparently deprecated according to this: https://github.com/Microsoft/azure-devops-cli-extension
It's unfortunate since the Azure DevOps web UI still points to both this page via https://aka.ms/vstscli-installdocs . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1e67b4-3a87-9c23-0c5e-7ece623c905c
* Version Independent ID: dff5ba58-c6b9-ba1c-68ed-25fddb657724
* Content: [Set up credentials for the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/authenticate?view=vsts-cli-latest)
* Content Source: [latest/docs-ref-conceptual/authenticate.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/authenticate.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mbrancato** [comment]
The links and the verbiage from Azure DevOps should probably point here: https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages

Until I found this repo, I had no clue it was replaced.
![image](https://user-images.githubusercontent.com/8493275/53280447-3457e980-36e8-11e9-870a-a130fd24bf52.png)

**Comment by atbagga** [comment]
@geverghe @mitchdenny  Any timeline on when the Web UI would be updated?

**Comment by mitchdenny** [comment]
We've got a bug tracking it now. No ETA yet but I'm hoping we can slip it in for the next sprint.

**Comment by cdietschrun** [comment]
When is this going to be updated?

**Comment by zarenner** [comment]
@jmyersmsft to comment on when the updates here will be rolled out

**Comment by jmyersmsft** [comment]
The fix is checked in and will roll out some time in the next few weeks.

**Comment by atbagga** [comment]
Deployed to most organizations. Should be available in remaining ones by next week. 
Closing the issue.
