### ISSUE TITLE
[Enhancement Request] az pipelines build list should support listing top builds in sorted order, sorting order should support finish time, start time etc

### ISSUE THREAD

**Issue by tehho** [Azure/azure-devops-cli-extension#465]
**Is your feature request related to a problem? Please describe.**
Well sort of. az pipelines build list --top does not list "top" builds. 

**Describe the solution you'd like**
az pipelines build list --top return top X sorted by date, release date or finnish date your choice

**Additional context**
Love the product

**Comment by atbagga** [comment]
Pipelines commands are already being revamped and the work is in progress. We will take care of this enhancement in the same. The work is being tracked in #333 

Keeping this open for tracking purpose.

**Comment by atbagga** [comment]
This will be available in the next release. 0.5.0

**Comment by atbagga** [comment]
@tehho The query order is now an option in both ```az pipelines list``` and ```az pipelines runs list`` commands. 
Thank you for your contribution!

**Comment by justinchuby** [comment]
Does `az pipelines **build** list` support the query order? It does not from glancing the documentation and testing with the cli.
