### ISSUE TITLE
[Feature Request] Manage permissions

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#472]
**Is your feature request related to a problem? Please describe.**
Ability to manage user permissions - view all permissions and update permission.

**Describe the solution you'd like**
Need a command to view all permission for a user and also to update them.

**Additional context**
NA

Spec against which we are actively developing the permission management commands:
## Permission Management 
| Scenario | Command | Open Questions |
|--|--|--|
| I want to view the permissions I have for a namespace| `az devops security permission list  --namespace-id --subject`| List all tokens for this user/group|
| I want to add a permission for a namespace| `az devops security permission add --subject --namespace-id --token --allow-bit --deny-bit`|  Set allow/deny permission bits for a given user/group and token|
| I want to remove a permission for a namespace| `az devops security permission reset --permissions --subject --namespace-id --token `|  |
| I want to reset all permission for a namespace| `az devops security permission --reset-all --subject --namespace-id --token |  |
| Show resolved permissions| `az devops security permission show --subject --namespace-id --token `| |
| I want to view all namespaces available| `az devops security permission namespace list`| |
| I want to view all permissions available in a namespace| `az devops security permission namespace show --namespace-id`| |

**Comment by ishitam8** [comment]
Permission related commands will be available in the next release (i.e 0.9.0.)
