### ISSUE TITLE
Management of variable groups

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-devops-cli-extension#479]
**Is your feature request related to a problem? Please describe.**
Currently creating a variable group is a manual task only available from the Azure DevOps portal. For open source projects where I'm sharing Pipelines YAML and referencing variable groups in them, this is a major pain.

I simply have to instruct users to go set the variable group up manually and call it a specific name, then tell them which variables to set in there. It's very clumsy

**Describe the solution you'd like**
The CLI should allow for doing this, e.g. via `az devops var-group create` command and potentially an input YAML file which sets the variable defaults. In addition a `az devops var-group variable set` command to allow setting of variables in a group. This would allow for automated scripting of setups

**Additional context**

**Comment by atbagga** [comment]
## Command structure proposed for Variable-Group Commands

|Command                            |Description                      |Params                                                                       |Table Output Response               |Comments                                                                                         |
|-----------------------------------|---------------------------------|-----------------------------------------------------------------------------|------------------------------------|-------------------------------------------------------------------------------------------------|
|az pipelines variable-group create|Create a new Variable Group      |org, project, name, description, variables, type (vsts, azurekeyvault)       |name, id, description, num_variables|                                                                                                 |
|az pipelines variable-group update|Update existing variable group   |org, project, group-id.. Update name, description, type, variables           |name, id, description, num_variables|                                                                                                 |
|az pipelines variable-group list  |List variable groups in a project|org, project, group-name, action-filter, continuation-token, query-order, top|name, id, description, num_variables|list with ids  is another API, so we can have that functionality in the same command if required.|
|az pipelines variable-group show  |Show details on a variable group |org, project, group-id                                                       |name, id, description, num_variables|                                                                                                 |
|az pipelines variable-group delete|Delete a variable group          |org, project, group-id                                                       |                                    |                                                                                                 |


Rest API docs [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups?view=azure-devops-rest-5.0)

**Comment by atbagga** [comment]
Variable group management commands will be available  in 0.12.0 in next couple of weeks. 

Filed a new issue to track - AzureKeyVault groups #723

**Comment by ravensorb** [comment]
It would be great to be able to manage security on variable groups as well.

**Comment by atbagga** [comment]
@ravensorb avoid commenting on closed issues as they might never get noticed. Feel free to file a new issue and we will prioritise it based on upvotes.
