### ISSUE TITLE
[Feature Request] Az devops support for managing agents and agent pools

### ISSUE THREAD

**Issue by vitru** [Azure/azure-devops-cli-extension#504]
az devops is currently missing ability to list agent pools and agents in a particular pool. This is useful for scripting commands against an agent pool and figuring out agents that are disabled/offline. Also, it should be possible to manage user capabilities from CLI.
Thanks!

**Comment by atbagga** [comment]
To start with we can add the following commands - 


API [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/?view=azure-devops-rest-5.1) for Agents, pools and queues.

|Command                |Description                |Params                                                                                                                                                                 |Response|Comments|
|-----------------------|---------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|--------|
|az pipelines pool list |list agent pools           |Org, Filter params - name, properties, type, actions                                                                                                                   |        |        |
|az pipelines pool show |Show details of a pool     |Org, pool id                                                                                                                                                           |        |        |
|az pipelines agent list|List agents                |Org, pool id, Filter option - Name, demands(that agent can fulfil), Include Details option -  capabilities, properties - list, assigned request, last completed request|        |        |
|az pipelines agent show|Show details of an agent   |Org, pool id, agent id, Include Details option -  capabilities, properties - list, assigned request, last completed request                                            |        |        |
|az pipelines queue list|List agent queues          |Org, project, Filter on - queue name and action filter (user has manage or use permission on it)                                                                       |        |        |
|az pipelines queue show|Show details of agent queue|Org, project, queue id, Filter on action filter                                                                                                                        |        |        |

**Comment by atbagga** [comment]
Linking to #457 where queue-id is consumed. These commands will allow the user to fetch the queue-id where they want to trigger the pipeline.

**Comment by atbagga** [comment]
@vitru The new commands are available in release 0.11.0. 
Thanks!
