### ISSUE TITLE
[Feature Request] Allow force flag for az repos policy create

### ISSUE THREAD

**Issue by onlyutkarsh** [Azure/azure-devops-cli-extension#519]
**Is your feature request related to a problem? Please describe.**
If the branch policy already exists, we will need to use `az repos policy update` command. This means I need to first get the policy id. Getting the policy id for a repo is not intuitive especially because `az repos policy list` lists just repository id
![image](https://user-images.githubusercontent.com/2685029/55323114-12375100-5476-11e9-996b-7f80aa239d48.png)

**Describe the solution you'd like**
Allow me to set the `--force` flag for `az repos policy create` command

**Comment by geverghe** [comment]
Including scenario context:
We have close to 50+ repos and new ones getting created each day. Apart from “required reviewer” and “build validation” policy types (which change per repo), I would like to keep following (4 below) policies same and in sync for all repos. I would like to run this using az devops cli as part of scheduled pipeline.
 
1.	Minimum number of reviewers
2.	Work item linking
3.	Comment requirements
4.	Require a merge strategy
 
This will ensure, even if policy is changed by someone manually, the pipeline will re-apply them in next run. Hope that makes sense.

**Comment by geverghe** [comment]
Hey @onlyutkarsh - circling back on this requirement - this to ensure that for every new scheduled pipeline run, the policies must be reset (in case it has been altered) using the policy <type-of-policy> update command. To address the grievance, in the policy list command, the policy id is rendered in both the table output and available via the json. Therefore, for the approver-count policy, you could potentially run
1. `az repos policy list`
2. Fetch the policy ID from the listing
3. Update the policy using `az repos policy approver-count update` command.

Will this work?

**Comment by onlyutkarsh** [comment]
Hello @geverghe - I will test updating the policy using `approver-count update` command over the weekend. 

> 2\. Fetch the policy ID from the listing

Regarding this, I just checked that policy ID gets changed if I just disable the policy and enable it again after a few minutes [screenshot below]. In such a scenario, it would be difficult to hardcode this in the pipeline. If policy id changes my pipeline would break offline and I have to run the command manually. I think it will not be possible to automate.

![image](https://user-images.githubusercontent.com/2685029/59303971-46f23080-8c8f-11e9-9c58-807495d61f1d.png)

**Comment by geverghe** [comment]
@onlyutkarsh  - Let me look into this. I did a quick check and the ID remains the same even after 10 minutes of change. I will loop in the team as well to try and repro this. Will keep you posted on progress.

**Comment by onlyutkarsh** [comment]
@geverghe I think I can consistently repro now. Check my commands and my settings in the Azure DevOps in the screenshot below. Hope it helps.

![image](https://user-images.githubusercontent.com/2685029/59337326-46da4b00-8cf8-11e9-905f-f101b983b321.png)

**Comment by atbagga** [comment]
@onlyutkarsh  When you uncheck the box from UI it sends a delete call not an update call so the policy is effectively deleted. (Verified in network trace)

If you enable/disable policy from the command line it will not change the Id of the policy since it is an update operation.

```
az repos policy approver-count update --id 40 --enabled true
az repos policy approver-count update --id 40 --enabled false
```

So you can effectively hardcode the policy id in the pipeline. Hope that helps.

**Comment by geverghe** [comment]
@onlyutkarsh - I am closing this issue. Feel free to reactivate the issue in case the above resolution does not help.
