### ISSUE TITLE
[Feature Request] Add support for "asOf" in work item get 

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-devops-cli-extension#535]
**Is your feature request related to a problem? Please describe.**
While getting a work item, I can get work item snap shot at a particular point of time using 
https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20item?view=azure-devops-rest-5.0#get_work_item_with_asof_parameter

**Describe the solution you'd like**
e.g. If you want a new command to be added, what would it do?

**Additional context**

@geverghe @snankani : This seems to be one of the use case which is currently not exposed in UI (or at least not a straight forward thing to achieve). So this should be a good value addition to CLI

cc: @ishitam8

**Comment by atbagga** [comment]
+ Add support for other couple of parameters - expand, fields.
