### ISSUE TITLE
`az repos pr create --open` should publish the branch

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-devops-cli-extension#539]
**Is your feature request related to a problem? Please describe.**
`git push -u $branch $branch` is redundant and tedious

**Describe the solution you'd like**
Running the command `az repos pr create --open` should automatically push the current branch to `origin` before continuing with the current behavior.  If necessary, it can be implemented conditionally with a `--push` or `--publish` switch

**Comment by atbagga** [comment]
@chriskuech  What happens if the push fails? You will still have to go to git and fix through rebase or force push. Should the command fail if push fails or still try to create a PR, won't the command behaviour be uncertain in that case?

**Comment by chriskuech** [comment]
I agree, so it would probably make sense to put it behind that `--publish` or `--push` switch, which would by definition push and set the upstream branch, and fail if the git call fails.

**Comment by atbagga** [comment]
I am not convinced push functionality should be merged in the pr command. 
User can create aliases or scripts to do this stuff as per custom needs.

@geverghe Please take a look.

**Comment by chriskuech** [comment]
I don't think that is a fair assessment, as the same exact comment an be said for the `--open` switch as well.  In fact, until this command was released, I had all the functionalities of the command scripted.  Of my 46 line git helper script, `az repos pr create --open` replaces all functionality _except_ publishing the branch, which is a non-obvious command.  Why not remove the need for a helper script entirely with on "opt-in" solution like another switch, just as you do with `--open`?

**Comment by snankani** [comment]
At this point, we are maintaining the demarcation of git commands and Azure DevOps command, so we will relook at this feedback in future.
