### ISSUE TITLE
[Bug] az devops user add --license-type "none" returns "Invalid License type."

### ISSUE THREAD

**Issue by g-macd** [Azure/azure-devops-cli-extension#545]
Running this command:
az devops user add --license-type "none" --email-id "sample@contoso.com" --organization "https://{myorg}.visualstudio.com" --send-email-invite "false"

returns with: "Invalid license type."

I have been able to add "express" or "stakeholder" license types, but i need to be able to add Visual Studio Subscriber users. I've tried "advanced", "none" and "professional", all give the same error

**To Reproduce**
Azure Cli Version: 2.0.62
Azure-Devops extension version: 0.4.0

1. login using az login
2. Run command above
3. See error

**Expected behavior**
User added to Azure DevOps with 'Visual Studio subscriber' license

**Comment by ishitam8** [comment]
Hi,

Can you share the debug logs for this issue ? [Run the same command with '--debug' switch.]

Also, you can see the list of user license types available for your account by using this API 
[User Entitlement Summary](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlement%20summary/get?view=azure-devops-rest-5.0) . There is no command available for this in CLI currently. You will be able to see the list of license types available for your account in the response [availableAccessLevels] . Kindly share this list as well.

**Comment by g-macd** [comment]
[debug_log.txt](https://github.com/Azure/azure-devops-cli-extension/files/3092410/debug_log.txt)
[user_entitlement_summary.txt](https://github.com/Azure/azure-devops-cli-extension/files/3092411/user_entitlement_summary.txt)

I've attached both of those (with sensitive information removed). I had looked at the User Entitlement Summary previously, it seems to show a "none" option available to me.

**Comment by ishitam8** [comment]
Hi,

We have fixed the error message in case of Invalid license type in version 0.5.0.
I would request you to run the command again with latest release
If you are still getting the error, I am assuming the API doesn't allow you to set license-type as None for that account.
Also, I am unable to see response for the API call in your attachments.
Let me know if latest release works for you.

**Comment by g-macd** [comment]
Hi,

I'm now getting a different error - _A user cannot be assigned an Account-None license._

I'm guessing that this means what you've said is correct, and i can't assign this via the API - will have to resort to the gui.

Thanks,
Glen.

**Comment by g-macd** [comment]
According to [this page](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlements/add?view=azure-devops-rest-5.0#accountlicensetype) it is a valid value.

Is there likely to be a bug with the REST API?

**Comment by geverghe** [comment]
@ishitam8  - Would you be able to follow up on this to confirm if none is a valid input or not?

**Comment by ishitam8** [comment]
Hi,

Removed **none** from the list of valid user access-level. [API documentation will be updated soon]
Also, to add **Visual studio subscriber** , you can just add users  with basic or stakeholder access levels, and their visual studio subscription would be picked up as soon as user logs in to the account. 

I hope this solves your issue.

Thanks for reporting this.

**Comment by darryljamesheath** [comment]
@ishitam8 This doesn't seem to be the case anymore - [ADO documention](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops#visual-studio-subscription-access).

It would be good to have the ability to set a user access level to 'visual studio subscriber' directly with the CLI.

Thanks.

**Comment by ishitam8** [comment]
@ashishonce , @narula0781 . Could you please take a look?
