### ISSUE TITLE
[Bug] Allow branch policies to be bypassed when completing a pull request

### ISSUE THREAD

**Issue by jackjfrost** [Azure/azure-devops-cli-extension#548]
It appears that there is no way to bypass branch policies when completing a pull request via the az devops CLI, even if the pull request has the flags set that should allow the policies to be bypassed.
```
% az repos pr complete --id 2820
This pull request requires an explicit override to bypass policies that aren't currently passing.
```

When showing the attributes of that pull request, the following is returned:
```
  "completionOptions": {
    "bypassPolicy": true,
    "bypassReason": "force",
    "deleteSourceBranch": true,
    "mergeCommitMessage": "forcing",
    "mergeStrategy": "squash",
    "squashMerge": true,
    "transitionWorkItems": true
  },

```

Assuming the user attempting to bypass the policies is in a group that has those permissions (Bypass policies when completing pull requests) allowed for the target repo, I would think that the 'complete' option should succeed.

**Comment by atbagga** [comment]
Fix is merged to master. Should be available in version 0.9.0 and later.
ETA for release Week of 17th May.

**Comment by jackjfrost** [comment]
This appears to be broken again:

~$ az repos pr update --org <myorg> --id 13469 --status "completed" --bypass-policy true --bypass-policy-reason "force"
Core Promote Pipeline must succeed to update master.

**Comment by jackjfrost** [comment]
I also tried doing the above in two steps and that didn't work either:

~$ az repos pr update --org <myorg> --id 13469 --bypass-policy true --bypass-policy-reason "force"
~$ az repos pr show --id 13469 --org <myorg> | grep bypass -i
    "bypassPolicy": true,
    "bypassReason": "force",
~$ az repos pr update --org <myorg> --status completed --id 13469
Core Promote Pipeline must succeed to update master.

**Comment by jackjfrost** [comment]
Nevermind, found my issue.
