### ISSUE TITLE
[Bug] Unable to specify matchkind when creating policy from command line

### ISSUE THREAD

**Issue by michaelmcmaster** [Azure/azure-devops-cli-extension#563]
**Describe the bug**
Creating a policy on a branch from which others will inherit (ex: `release/*`) appears to work in the command line, and appears to be applied correctly when inspecting the policy in the portal (`Project` -> `Repo` -> `release/*`) the portal shows the policy being set.  However, the policy is not shown in the pull request.  After a bit of debug, the policy, as created via the command line (see recreate step 3) with a setting scope having `matchKind` of `Exact`.  When creating the identical policy via the portal, the `matchKind` is properly set to `Prefix`.  There doesn't appear to be a way to specify `matchKind` via the command line.

**To Reproduce**
Azure Cli Version: 2.0.60
Azure-Devops extension version: 0.5.0

1. Create a new repo and create a branch to be used for releases (`release/0.0.0`)
2. login using `az login`
3. Run command to create a policy on the `release/*` branch hierarchy:
`az repos policy approver-count create --detect --repository-id $repoId --branch release/* --allow-downvotes false --creator-vote-counts true --minimum-approver-count 2 --is-blocking true --is-enabled true --reset-on-source-push true`
4. Observe, in the DevOps portal, that the policy *appears* to be correctly applied to `release/*`.  5. Create a change on `master` and commit it
6. Create a pull request from `master` to `release/0.0.0`
7. Observe that the policy is not applied to the pull request (ie. doesn't require approvals from two people)

**Expected behavior**
There should be a way to set matchKind via the `az repos policy` command line, or infer the `matchKind` from the branch ending with a wildcard.

**Comment by atbagga** [comment]
@michaelmcmaster The fix was released today. Checkout the updated extension.

**Comment by michaelmcmaster** [comment]
@atbagga Many thanks.  I added the `--branch-match-type Prefix` property/value to the `az repos policy xxx create` command line, and things are working well now.  The only issue I had was finding that I needed to specify the `--branch` **without** the wildcard.

**Comment by JohannTIM** [comment]
This would be nice to document somewhere

**Comment by SheplX** [comment]
> @atbagga Many thanks. I added the `--branch-match-type Prefix` property/value to the `az repos policy xxx create` command line, and things are working well now. The only issue I had was finding that I needed to specify the `--branch` **without** the wildcard.

assume that I have some branches with the prefix "release" I used this --branch-match-type Prefix with --branch to select any branch matching the prefix but the policy not being applied on any branch maching the same prefix I even used http request to do it but not works. any idea?

**Comment by SheplX** [comment]
> @atbagga Many thanks. I added the `--branch-match-type Prefix` property/value to the `az repos policy xxx create` command line, and things are working well now. The only issue I had was finding that I needed to specify the `--branch` **without** the wildcard.

assume that I have some branches with the prefix "release" I used this --branch-match-type Prefix with --branch release to select any branch matching the prefix but the policy is not being applied on any branch matching the same prefix I even tried to set it using API request but not works. any idea?
