### ISSUE TITLE
[Feature Request] Add -p or --project to work-item show

### ISSUE THREAD

**Issue by srajkovic** [Azure/azure-devops-cli-extension#570]
**Is your feature request related to a problem? Please describe.**
I can't open work items if they live in a separate project from the repo that I'm in.

**Describe the solution you'd like**
`--project -p` to be supported on `work-item show` like it is on `work-item create` and `work-item delete`.

I searched and couldn't find an existing open issue for this, feel free to link me to one and close this if one exists.

**Comment by gauravsaralMs** [comment]
@srajkovic : work-item show needs --id to show the work-item for the given org. 
show is not dependent on project

if there is something missing please add more details like
what you ran
what happened
what you expected to happen and why

**Comment by srajkovic** [comment]
Huh, yesterday it seemed like it wasn’t working with just the ID, but now
it does appear to be. Sorry, and thanks!

-- 
Stefan Rajkovic

Sent from mobile, please excuse any typos or brevity.

From: gauravsaralms <notifications@github.com> <notifications@github.com>
Reply: Azure/azure-devops-cli-extension
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 1, 2019 at 23:32:08
To: Azure/azure-devops-cli-extension
<azure-devops-cli-extension@noreply.github.com>
<azure-devops-cli-extension@noreply.github.com>
CC: Stefan Rajkovic <stefan@stefanrajkovic.com> <stefan@stefanrajkovic.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [Azure/azure-devops-cli-extension] [Feature Request] Add -p
or --project to work-item show (#570)

@srajkovic <https://github.com/srajkovic> : work-item show needs --id to
