### ISSUE TITLE
[Feature Request] `az repos pr create --draft` switch

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-devops-cli-extension#586]
**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to create a draft PR from the CLI.  If you mark the PR as a draft after the PR is created, a notification is sent out as if its a normal PR, therefore the PR must be marked as a draft during creation.

**Describe the solution you'd like**
A `--draft` switch on `az repos pr create` that marks the created PR as a draft.

**Comment by atbagga** [comment]
@chriskuech  you are probably on an older version of the extension. 
The functionality was added in 0.6.0. Here is the documentation link - https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/pr?view=azure-cli-latest#ext-azure-devops-az-repos-pr-create
