### ISSUE TITLE
[Bug] extension install expects name not id

### ISSUE THREAD

**Issue by rjfmachado** [Azure/azure-devops-cli-extension#595]
**Describe the bug**
az devops extension install fails with error:
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='extmgmt.dev.azure.com', port=443): Max retries exceeded with url: /ricardma/_apis/ExtensionManagement/InstalledExtensionsByName/714e6355-e46f-4e90-b7e0-7336889543a6/08ff4446-6ed0-41f2-a848-807e0837b83d (Caused by ResponseError('too many 500 error responses',))

**To Reproduce**
azure-cli                         2.0.64
azure-devops (0.8.0)

az devops extension search --search-query terraform --query "[?extensionId=='08ff4446-6ed0-41f2-a848-807e0837b83d']"
az devops extension install --extension-id 08ff4446-6ed0-41f2-a848-807e0837b83d --publisher-id 714e6355-e46f-4e90-b7e0-7336889543a6

command works with:
az devops extension install --extension-id azure-pipelines-tasks-terraform --publisher-id charleszipp

**Expected behavior**
I expect to pass the id's or have extension-name and publisher-name parameters.

**Comment by gauravsaralMs** [comment]
Thanks for reporting this @rjfmachado
