### ISSUE TITLE
[Bug] The command  fails when the title consists of two space separated words in quotes

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#606]
**Describe the bug**
Part of our workflow involves git alias commands which rely on Git Bash.
This command works in Git Bash:
{{{
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ az.cmd repos pr create --work-items 49 --title flower --target-branch refs/heads/master --output table
ID    Created     Creator                Title    Status    Repository
----  ----------  ---------------------  -------  --------  --------------
96    2019-05-10  daclash@microsoft.com  flower   Active    MyFirstProject
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ az repos pr abandon --output table --id 96
ID    Created     Creator                Title    Status     Repository
----  ----------  ---------------------  -------  ---------  --------------
96    2019-05-10  daclash@microsoft.com  flower   Abandoned  MyFirstProject
}}}

This command fails.  The difference is that the title consists of two space separated words in quotes.
{{{
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ az.cmd repos pr create --work-items 49 --title "flower pencil" --target-branch refs/heads/master --output table
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
}}}

It looks like the "%*" is not preserving the quotes around the title parameter.
{{{
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ cat "/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az.cmd"
::
:: Microsoft Azure CLI - Windows Installer - Author file components script
:: Copyright (C) Microsoft Corporation. All Rights Reserved.
::
@IF EXIST "%~dp0\..\python.exe" (
  "%~dp0\..\python.exe" -IBm azure.cli %*
) ELSE (
  echo Failed to load python executable.
  exit /b 1
)
}}}

The following bash wrapper works.  The '"$@"' preserves quotes around parameters.
{{{
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ cat ~/bin/az
#!/bin/bash
"/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/python.exe" -IBm azure.cli "$@"
}}}

Example using the bash wrapper:
{{{
daclash@MININT-SBREK3J MINGW64 ~/src/MyFirstProject (personal/daclash/master-49)
$ az repos pr create --work-items 49 --title "flower pencil" --target-branch refs/heads/master --output table
ID    Created     Creator                Title          Status    Repository
----  ----------  ---------------------  -------------  --------  --------------
97    2019-05-10  daclash@microsoft.com  flower pencil  Active    MyFirstProject
}}}

Is this issue something that may have been fixed recently?
{{{
PS C:\users\daclash\src\MyFirstProject> az --version | findstr azure-cli
You have 37 updates available. Consider updating your CLI installation.
azure-cli                         2.0.61 *

PS C:\users\daclash\src\MyFirstProject> az --version | findstr azure-devops
You have 37 updates available. Consider updating your CLI installation.
azure-devops                       0.4.0
}}}

**To Reproduce**
Azure Cli Version: 
2.0.61

Azure-Devops extension version: 
0.0.4

*Expected behavior**
Possible to create title which consists of space separated words included in quotes.

**Screenshots**
NA

**Debug logs**
NA

**Additional context**
Including the bug on behalf of Dan and Brian who sent this over via email.

**Comment by atbagga** [comment]
This is an azure cli issue. e.g. Following azure cli command also fails on bash - 
```az.cmd tag create -n "temporary tag"```

There are already related issues reported on their repo so I will wait for them to respond and then look at fixing it there.

**Comment by geverghe** [comment]
Closing this issue as this is an Azure CLI issue. Including the azure cli issues to follow up
https://github.com/Azure/azure-cli/issues/8560
https://github.com/Azure/azure-cli/issues/9204
