### ISSUE TITLE
[Feature Request] Idempotent az devops service-endpoint create

### ISSUE THREAD

**Issue by timja** [Azure/azure-devops-cli-extension#608]
**Is your feature request related to a problem? Please describe.**
If you run the below twice, then you get two service connections
```
az devops service-endpoint create --name timj-testing --service-endpoint-type azurerm --authorization-scheme ServicePrincipal  --azure-rm-tenant-id <tenant> --azure-rm-service-principal-id <sp> --azure-rm-service-principal-key <key> --azure-rm-subscription-id <sub>  --project CNP --organization https://dev.azure.com/org/ --azure-rm-subscription-name <sub-name>
```
![image](https://user-images.githubusercontent.com/21194782/57921347-11774480-7895-11e9-8fe9-3aa16d991cf2.png)

**Describe the solution you'd like**
If a service connection exists then update it

**Comment by gauravsaralMs** [comment]
Resource creation is generally not Idempotent.
Recommendation will be to not take this change:
Ping for triage @snankani  @geverghe

**Comment by geverghe** [comment]
Agree with @gauravsaralMs - from an experience point as well, the verb is create and we do not want a hidden update happening. It would lead to lack of predictability in what the command is doing.

**Comment by timja** [comment]
The az cli is idempotent in general though?
If you run create on things like:
* resource groups
* key vaults
* storage accounts

then it won't create another resource 
the only things I'm aware of that aren't idempotent are role assignments, creating SPs and creating ad apps

**Comment by geverghe** [comment]
We rely on the Azure DevOps REST APIs and it's corresponding design. In case of the Azure examples provided, the REST APIs have been designed as is, but the same is not true for Azure DevOps Service Endpoint REST API. For now, coming back to the need - may I ask where do you run into this issue? Is it while running a script or interactive use? Would it help if we built out the update and delete commands?

**Comment by timja** [comment]
Automating the creation of a service endpoint.
It's run in a script

Yes update and delete commands would also solve my usecase

But idempotency would be a great feature imo, given that the azure cli in general is idempotent.

**Comment by snankani** [comment]
Valid feedback. Right now CLI is completely dependent on api design so we can not support this at this point. We will percolate the feedback with respective team. 

As a workaround, a combination of other commands like SHOW/LIST and DELETE can be used if required to achieve idempotency in this case. Show and list commands are already available whereas delete service-endpoint will be release in upcoming version by next week.
