### ISSUE TITLE
[Feature Request] Delete service-endpoint

### ISSUE THREAD

**Issue by timja** [Azure/azure-devops-cli-extension#609]
**Is your feature request related to a problem? Please describe.**
I cannot delete a service endpoint via CLI

```
az devops service-endpoint [-h] {list,show,create}
```

**Describe the solution you'd like**
`az devops service-endpoint delete --name <name>`

**Additional context**
Relates to https://github.com/Azure/azure-devops-cli-extension/issues/608, as its not idempotent I wanted to do a delete and re-create but I can't do that

**Comment by gauravsaralMs** [comment]
Ping for triage @snankani @geverghe

**Comment by timja** [comment]
Thanks for the quick turn around on this!

**Comment by azurekid** [comment]
I cannot delete a service endpoint using CLI. 
Although I have all the required permissions the service endpoint will not be removed. The cli does ask for confirmation for removal. 

Tried to use the connection ID and connection Name.

**Comment by gauravsaralMs** [comment]
@azurekid : can you please share the debug logs?
add `--debug` to your command and share the logs (please make sure to remove any secrets the logs might contains)
