### ISSUE TITLE
[Feature Request] 'Variables' and 'Variable groups' parameter for az pipelines create|update

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/azure-devops-cli-extension#639]
**Is your feature request related to a problem? Please describe.**
Some variables can't be in the azure-pipelines.yaml file in source control. For that we have the ability to edit via the UI the variables of the pipeline definition. It would be ideal to have the ability to set `variables` while leveraging `az pipelines create` and `az pipelines update`.

**Describe the solution you'd like**
`az pipelines create --variables key1=value1 key2=value2` same for `az pipelines update`

**Describe alternatives you've considered**
The alternative is to do that via the UI by editing the pipelines definition, but not very efficient for automation.

**Comment by geverghe** [comment]
Got it; adding it to backlog to be prioritized.

**Comment by LaurentLesle** [comment]
Variable group linked to Azure Key Vault keys would be a great addition as well

**Comment by juandura** [comment]
Hi, any estimated delivery date for this feature?

**Comment by atbagga** [comment]
@juandura 

The new commands to manage variables and variable groups are in PR #711 and should be available in next release in couple of weeks time.
Note: Azure Key vault linked groups are not part of this PR and might be added later.

**Comment by atbagga** [comment]
The commands released as part of this change are the following two command groups- 
1. az pipelines variable 
1. az pipelines variable-group 

You can manage creating variables normal/secrets using commands in these two groups. 
e.g. `az pipelines variable create --name MyTestVar --value TestValue --pipeline-id 1`

Linking variables and variable groups to pipelines is recommended to be done through yaml file for yaml based pipelines. Documentation for the same is here - https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml

**Comment by atbagga** [comment]
Closing this issue and creating a new one to follow up on the AzureKeyVault groups whose APIs are not documented which is blocking the feature.

Will be available in 0.12.0
ETA for release is Next couple of Weeks.
