### ISSUE TITLE
[Bug] Policy updates no longer support "--is-blocking true --is-enabled true"

### ISSUE THREAD

**Issue by IvanJosipovic** [Azure/azure-devops-cli-extension#644]
**Describe the bug**

In version 0.9.0 certain commands no longer support "--is-blocking true --is-enabled true" parameters which worked in 0.8.0

This appears to affect:
az repos policy approver-count update 
az repos policy comment-required update 
az repos policy build update 
az repos policy work-item-linking update 

**To Reproduce**
Azure Cli Version: 
azure-cli (2.0.64)

Azure-Devops extension version: 
azure-devops (0.9.0)

1. login using az login
2. setup defaults..
3. az repos policy approver-count update --branch master --is-blocking true --is-enabled true --minimum-approver-count 1 --repository-id $repoID --org $org --project $projectName --id $policyId
4. See error "az: error: unrecognized arguments: --is-blocking true --is-enabled true"

**Expected behavior**
"--is-blocking true --is-enabled true" parameters should work as per documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/9521987/58594072-89445800-8221-11e9-8492-deebbdfbbec3.png)

**Debug logs**
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04E8A150>]
cli.azure.cli.core.parser : az: error: unrecognized arguments: --is-blocking true --is-enabled true
az: error: unrecognized arguments: --is-blocking true --is-enabled true
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {repos} ...
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2579 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\ivanj\.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 0.832 seconds.

**Comment by gauravsaralMs** [comment]
Apologies for the issue @IvanJosipovic .
In 0.9.0 release we took a breaking change and now this command will take blocking and enabled param

````bash
Command
    az repos policy approver-count update : Update approver count policy.

Arguments
    --id --policy-id [Required] : ID of the policy.
    --allow-downvotes           : Whether to allow downvotes or not.  Allowed values: false, true.
    --blocking                  : Whether the policy should be blocking or not.  Allowed values:
                                  false, true.
    --branch                    : Branch on which this policy should be applied. For example:
                                  master.
    --branch-match-type         : Determines how the branch argument is used to apply a policy. If
                                  value is 'exact', the policy will be applied on a branch which has
                                  an exact match on the --branch argument. If value is 'prefix' the
                                  policy is applied across all branch folders that match the prefix
                                  provided by the --branch argument.  Allowed values: exact, prefix.
    --creator-vote-counts       : Whether the creator's vote counts or not.  Allowed values: false,
                                  true.
    --detect                    : Automatically detect organization.  Allowed values: false, true.
    --enabled                   : Whether the policy is enabled or not.  Allowed values: false,
                                  true.
    --minimum-approver-count    : Minimum number of approvers required. For example: 2.
    --org --organization        : Azure Devops organization URL. Example:
                                  https://dev.azure.com/MyOrganizationName/.
    --project -p                : Name or ID of the project.
    --repository-id             : Id of the repository on which to apply the policy.
    --reset-on-source-push      : Whether to reset source on push.  Allowed values: false, true.

Global Arguments
    --debug                     : Increase logging verbosity to show all debug logs.
    --help -h                   : Show this help message and exit.
    --output -o                 : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                  yaml.  Default: table.
    --query                     : JMESPath query string. See http://jmespath.org/ for more
                                  information and examples.
    --subscription              : Name or ID of subscription. You can configure the default
                                  subscription using `az account set -s NAME_OR_ID`.
    --verbose                   : Increase logging verbosity. Use --debug for full debug logs.
````

As the release was done last night so docs are yet still not updated.
we will follow up to get the docs updated as soon as possible and again apologies for the inconvenience.

cc: @snankani  @geverghe

**Comment by atbagga** [comment]
@IvanJosipovic This change was done to be more consistent with the Azure-CLI naming paradigm. 

You might have to sync up your scripts with the change, since the parameter name is changed. If you still have concerns please feel free to raise an issue.
