### ISSUE TITLE
[Enhancement] Enhancing the listing experience for long lists in interactive mode 

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-devops-cli-extension#650]
**Is your feature request related to a problem? Please describe.**
Long lists in interactive mode take a lot of space and need scrolling up and down on the console. 

**Describe the solution you'd like**
Paginated output will be a better way to show these lists for selection.

**Comment by atbagga** [comment]
For consideration: 

Sample listing experience - https://user-images.githubusercontent.com/11888714/58624232-641d1b80-82ed-11e9-8bc1-5692af8d78bf.gif

Code is here: https://github.com/atbagga/PythonSamples/blob/996a4f3a271195a1cb95f0da24da1ece9759cdaf/promptlist.py#L1

**Comment by geverghe** [comment]
Closing this issue for now. To be re-activated if required.
