### ISSUE TITLE
[bug] --azure-rm-service-principal-key missing service-endpoint create

### ISSUE THREAD

**Issue by Cloud217** [Azure/azure-devops-cli-extension#659]
**Describe the bug**
When using az devops create service-endpoint the argument: --azure-rm-service-principal-key is not recognized anymore
**To Reproduce**
Azure Cli Version: 
   2.0.65

Azure-Devops extension version: 

azure-devops (0.10.0)

1. login using az login
2. setup defaults..
3. Run command az devops service-endpoint create 
4. notice that the argument for the service principal key is missing

**Comment by atbagga** [comment]
@Cloud217  We took a few [breaking changes in the release 0.9.0](https://github.com/Azure/azure-devops-cli-extension/releases/tag/20190527.4). This is one of them.
 
Reason for change - accepting secrets as part of command params is not recommended. You can either put the key interactively or use an environment variable for the same in automation use cases. 

Refer release notes link above for more info.
