### ISSUE TITLE
Listing users question

### ISSUE THREAD

**Issue by wi5nia** [Azure/azure-devops-cli-extension#662]
As the new users management is not yet documented a short question - when I do:

`az devops users list --top 1000`

in the result .json file I get to elements: **items** and **members** which both basically hold different users list.

What is the difference?

**Comment by geverghe** [comment]
Would this documentation help - https://docs.microsoft.com/cli/azure/ext/azure-devops/devops/user?view=azure-cli-latest?

**Comment by ishitam8** [comment]
Hi @wi5nia ,

We resort to  [User list API](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlements/get%20user%20entitlements?view=azure-devops-rest-5.0) and we are checking back with the team on the significance of both. Will update once I hear back.

**Comment by ishitam8** [comment]
HI @wi5nia  ,

As per the guidance from API team, you should consume members list from the json object. [Table output consumes the same]

**Comment by wi5nia** [comment]
So what does the items object contain? What is the difference? Why it is there?

**Comment by ishitam8** [comment]
Both **members** and **items** are collection of the member entitlement objects only. I have raised the query with team which owns the API, they would update the API documentation soon. We recommend you to use members object from the response. Hence, closing this. Please re-open if you have any more queries.
