### ISSUE TITLE
[Bug]"security group list" fails for on-prem Azure DevOps 2019

### ISSUE THREAD

**Issue by sevaa** [Azure/azure-devops-cli-extension#666]
**Describe the bug**
The group list command fails on my on-prem instance.

**To Reproduce**
Azure Cli Version: 2.0.61

Azure-Devops extension version:  0.10.0

1. login using az login --org http://tfs.acme.com:8080/tfs/MyCollection/ , provide a PAT
2. Run command "az devops security group list -p MyProject --org http://tfs.acme.com:8080/tfs/MyCollection/"
4. See error:
"API resource location 048aee0a-7072-4cde-ab73-7af77b1e0b4e is not registered on http://tfs.acme.com:8080/tfs/MyCollection."

**Debug logs**
Command arguments: ['devops', 'security', 'group', 'list', '-p', 'AMBIS', '--org', 'http://tfs.niaid.nih.gov:8080/tfs/Admin/', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03A12348>, <function OutputProducer.on_global_arguments at 0x03913150>, <function CLIQuery.on_global_arguments at 0x03931D68>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.005 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.010 seconds.
Loaded module 'appservice' in 0.009 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.011 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.003 seconds.
Loaded module 'botservice' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.005 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.004 seconds.
Loaded module 'container' in 0.004 seconds.
Loaded module 'cosmosdb' in 0.006 seconds.
Loaded module 'dla' in 0.007 seconds.
Loaded module 'dls' in 0.005 seconds.
Loaded module 'dms' in 0.004 seconds.
Loaded module 'eventgrid' in 0.004 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.004 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.003 seconds.
Loaded module 'keyvault' in 0.008 seconds.
Loaded module 'kusto' in 0.004 seconds.
Loaded module 'lab' in 0.005 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.007 seconds.
Loaded module 'network' in 0.028 seconds.
Loaded module 'policyinsights' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.007 seconds.
Loaded module 'redis' in 0.005 seconds.
Loaded module 'relay' in 0.004 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.006 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.004 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.005 seconds.
Loaded module 'sql' in 0.009 seconds.
Loaded module 'sqlvm' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.035 seconds.
Loaded module 'vm' in 0.014 seconds.
Loaded all modules in 0.307 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\valekseyev\.azure\cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: 'C:\Users\valekseyev\.azure\cliextensions'
Loaded extension 'azure-devops' in 0.041 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03A7B150>, <function register_ids_argument.<locals>.add_ids_arguments at 0x03A7B108>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x047E1270>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03913198>, <function CLIQuery.handle_query_parameter at 0x03931DB0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03A7B300>, <function handler at 0x04876780>, <function DevCommandsLoader.post_parse_args at 0x04CDF660>]
Extensions directory: 'C:\Users\valekseyev\.azure\cliextensions'
Extensions directory: 'C:\Users\valekseyev\.azure\cliextensions'
Getting credential: azdevops-cli:http://tfs.niaid.nih.gov:8080/tfs
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
PAT is present which can be used against this instance
Current cloud config:
AzureCloud
az login is not present
There are no active accounts.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\_profile.py", line 467, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\_profile.py", line 476, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valekseyev\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 61, in _get_credentials
    token_from_az_login = get_token_from_az_logins(organization, pat_token_present)
  File "C:\Users\valekseyev\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 118, in get_token_from_az_logins
    dummy_user = profile.get_current_account_user()     # noqa: F841
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\_profile.py", line 469, in get_current_account_user
knack.util.CLIError: There are no active accounts.
Getting credential: azdevops-cli:http://tfs.niaid.nih.gov:8080/tfs
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
Creating connection with personal access token.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Current cloud config:
AzureCloud
Azure devops telemetry enabled.
Logging telemetry to azure devops server.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache : Loading cache file: C:\Users\valekseyev\.azure-devops\python-sdk\cache\options.json
azext_devops.devops_sdk._file_cache : Loading cache file: C:\Users\valekseyev\.azure-devops\python-sdk\cache\resources.json
azext_devops.devops_sdk._file_cache : attempting to read file C:\Users\valekseyev\.azure-devops\python-sdk\cache\options.json as utf-8-sig
azext_devops.devops_sdk._file_cache : attempting to read file C:\Users\valekseyev\.azure-devops\python-sdk\cache\resources.json as utf-8-sig
azext_devops.devops_sdk.client : File cache hit for options on: http://tfs.niaid.nih.gov:8080/tfs/admin
azext_devops.devops_sdk.connection : File cache miss for resources on: http://tfs.niaid.nih.gov:8080/tfs/admin
azext_devops.devops_sdk.client : File cache hit for options on: http://tfs.niaid.nih.gov:8080/tfs/admin
azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
azext_devops.devops_sdk.client : POST http://tfs.niaid.nih.gov:8080/tfs/admin/_apis/CustomerIntelligence/Events
azext_devops.devops_sdk.client : Route template: _apis/{resource}/{areaId}
azext_devops.devops_sdk.client : Request content: [{'area': 'AzureDevopsCli', 'feature': 'devops', 'properties': {'Command': 'security group list', 'Args': 'scope project organization', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False}}]
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
msrest.universal_http : Configuring redirects: allow=True, max=30
azext_devops.devops_sdk.client : GET http://tfs.niaid.nih.gov:8080/tfs/admin/_apis/ResourceAreas
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Evaluate proxies against ENV settings: True
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
urllib3.connectionpool : Starting new HTTP connection (1): tfs.niaid.nih.gov:8080
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTP connection (1): tfs.niaid.nih.gov:8080
urllib3.connectionpool : http://tfs.niaid.nih.gov:8080 "POST /tfs/admin/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool : http://tfs.niaid.nih.gov:8080 "GET /tfs/admin/_apis/ResourceAreas HTTP/1.1" 200 143
azext_devops.devops_sdk.client : Response content: b'{"count":0,"value":[]}'
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client : Route template: _apis/{resource}/{*projectId}
azext_devops.devops_sdk.client : Api version '5.0'
azext_devops.devops_sdk.client : GET http://tfs.niaid.nih.gov:8080/tfs/admin/_apis/projects/AMBIS
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTP connection (1): tfs.niaid.nih.gov:8080
urllib3.connectionpool : http://tfs.niaid.nih.gov:8080 "GET /tfs/admin/_apis/projects/AMBIS HTTP/1.1" 200 440
azext_devops.devops_sdk.client : Response content: b'{"id":"5a732f69-135c-4a35-a0db-9c316fc9c307","name":"AMBIS","url":"http://tfs.niaid.nih.gov:8080/tfs/Admin/_apis/projects/5a732f69-135c-4a35-a0db-9c316fc9c307","state":"wellFormed","revision":381287,"_links":{"self":{"href":"http://tfs.niaid.nih.gov:8080/tfs/Admin/_apis/projects/5a732f69-135c-4a35-a0db-9c316fc9c307"},"collection":{"href":"http://tfs.niaid.nih.gov:8080/tfs/_apis/projectCollections/ee115ec1-9930-4beb-9316-14a6a55c96fa"},"web":{"href":"http://tfs.niaid.nih.gov:8080/tfs/Admin/AMBIS"}},"visibility":"private","defaultTeam":{"id":"33a16770-33af-4843-ad7f-ea40272f3e51","name":"AMBIS Team","url":"http://tfs.niaid.nih.gov:8080/tfs/Admin/_apis/projects/5a732f69-135c-4a35-a0db-9c316fc9c307/teams/33a16770-33af-4843-ad7f-ea40272f3e51"}}'
handling value error
API resource location 048aee0a-7072-4cde-ab73-7af77b1e0b4e is not registered on http://tfs.niaid.nih.gov:8080/tfs/admin.
Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.
telemetry.save : Save telemetry record of length 2381 in cache
telemetry.check : Negative: The C:\Users\valekseyev\.azure\telemetry.txt was modified at 2019-06-11 13:01:50.673203, which in less than 600.000000 s

**Comment by geverghe** [comment]
Hey @sevaa - thank you for reporting this. We currently only support Azure DevOps Services with the CLI. However, let us have a look, investigate and get back to you.

**Comment by ishitam8** [comment]
Hi @sevaa  ,

I checked with the corresponding team owning Graph APIs, unfortunately Graph APIs are not supported on Azure DevOps server 2019, thus you won't be able to use Group Management commands for on-prem.

**Comment by kripa-2019** [comment]
@ishitam8 @gauravsaralMs :
 I have a Case where both me & the Customer see : 
![AzCLI](https://user-images.githubusercontent.com/47343377/140410278-ef78aeaf-e649-4b1f-a087-cf5b15aedb50.png)

this is on Azure DevOps server 2020 , CLI version 2.20.3
