### ISSUE TITLE
Link azure add securitygroup into devops group broken

### ISSUE THREAD

**Issue by mlcroix** [Azure/azure-devops-cli-extension#667]
When we try to add an AAD security group to a DevOps group, we get this working without any problems. However, when we try to use az devops cli with the following commands we receive errors:

> mlcroix@DESKTOP-5LLM8OF:/mnt/d/coding/sourcetree/azureinfrastructure/zone/azureDevops$ az ad group show -g "xxx - core2"
> {
>   "deletionTimestamp": null,
>   "description": null,
>   "dirSyncEnabled": null,
>   "displayName": "xxx - Core2",
>   "lastDirSyncTime": null,
>   "mail": null,
>   "mailEnabled": false,
>   "mailNickname": "Banaan",
>   "objectId": "d3566cfb-f6b1-4c80-a704-9cf344cad30b",
>   "objectType": "Group",
>   "odata.metadata": "https://graph.windows.net/cec1f092-e2ed-495d-921e-6c8d55148a12/$metadata#directoryObjects/@Element",
>   "odata.type": "Microsoft.DirectoryServices.Group",
>   "onPremisesDomainName": null,
>   "onPremisesNetBiosName": null,
>   "onPremisesSamAccountName": null,
>   "onPremisesSecurityIdentifier": null,
>   "provisioningErrors": [],
>   "proxyAddresses": [],
>   "securityEnabled": true
> }
> mlcroix@DESKTOP-5LLM8OF:/mnt/d/coding/sourcetree/azureinfrastructure/zone/azureDevops$ az devops security group create --origin-id "d3566cfb-f6b1-4c80-a704-9cf344cad30b" --groups "vssgp.Uy0xLTktMTU1MTM3NDI0NS0yMDI4NjMxNzEtMjIzNjc4OTA3MC0yMTU2ODM4MzQ3LTExOTUxMDQ1NDAtMC0wLTAtMC0x" --scope project --project "xxxcore2"

**VS860004: Only Visual Studio created groups can be added to a custom scope.**

**Comment by alexdegroot** [comment]
To add a bit of context:
When using the UI it works, but using CLI it doesn't. This is pretty confusing.

**Comment by geverghe** [comment]
Hey @alexdegroot - thank you for reporting this. Let us have a look and get back to you.

**Comment by ishitam8** [comment]
Hi @alexdegroot ,

This is API limitation. But you can still add the AAD group to your VSTS groups in following way.
You need to pass --scope parameter as organization instead of project [Reason being AAD groups are materialized for an account and not just one project, thus to add AAD group to your VSTS group you will have to create it with organization scope.]

**Comment by geverghe** [comment]
Closing this issue. @alexdegroot - feel free to reopen this issue in case the above clarification and resolution do not help.

**Comment by MeIsAHoneyBee** [comment]
I've tried as per [ishitam8] commented [on Jun 17, 2019]: az devops security group create --origin-id 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' --groups 'vssgp.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' --scope organization --project 'Test-01' --org 'https://dev.azure.com/my-org/';

VS860004: Only Visual Studio created groups can be added to a custom scope.

Do you have any idea what else can be done?

**Comment by MeIsAHoneyBee** [comment]
Accidentally, I've got it working by removing the --project 'Test-01'

az devops security group create --origin-id 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' --groups 'vssgp.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' --scope organization --org 'https://dev.azure.com/my-org/';

**Comment by Nyamatmomin** [comment]
Hello,
I have tried the above suggested command.
For the groups I have selected Project Collection Valid Users

az devops security group create --origin-id '<object ID of the group from AD>' --groups 'vssgp.wwwwww' --scope organization --org 'https://dev.azure.com/my-org/'

I am getting the error
Operation returned a 500 status code.

I also tried adding the same group by giving a random name for --groups  in the format "vssgp.random" and this to didn't work.
az devops security group create --origin-id '<object ID of the group from AD>' --groups 'vssgp.devlopergrp' --scope "organization"
Operation returned a 500 status code.

Please help.
