### ISSUE TITLE
az devops login help text to include link to documentation

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#686]
**Is your feature request related to a problem? Please describe.**
Please include a link to the documentation that provides details on using a PAT Token.

**Describe the solution you'd like**
The link should detail how to use the PAT Token, especially provide visibility around using PAT via environment variable.

**Comment by atbagga** [comment]
@geverghe  Please share the documentation link which should be part of the help text.

**Comment by geverghe** [comment]
Here is the link - https://docs.microsoft.com/azure/devops/cli/log-in-via-pat

**Comment by atbagga** [comment]
Which help text do we intend to update with this link? and we will need a aka.ms link for it.

**Comment by geverghe** [comment]
Apologies for the delay:

Here is the aka.ms link - https://aka.ms/azure-devops-cli-auth

Objective - Provide information on various methods by which the PAT can be used to login - environment variable, interactive etc.

Where - az devops login command help
az devops login: Set the credential (PAT) to use for a particular organization. Refer https://aka.ms/azure-devops-cli-auth for more information on providing PAT as input.

**Comment by atbagga** [comment]
PR merged to master. Fix will be available in next release 0.12.0.
