### ISSUE TITLE
Work Item details in table format is not showing any data in the 'Assigned To' field.

### ISSUE THREAD

**Issue by suhaib16** [Azure/azure-devops-cli-extension#688]
**Description**
Work Item details in table format is not showing any data in the 'Assigned To' field.

**To Reproduce**
Azure CLI Version: 
Use az --version 
Look for something like-
azure-cli (2.0.64)

Azure-DevOps extension version: 
Use az --version
Look for something like-
Extensions:
azure-devops (0.8.0)

1. Login using az login
2. Setup defaults.
3. Run command:
`az boards query --wiql "select [System.Id], [System.Title], [System.AreaPath], [System.AssignedTo], [System.State] from workitems where [System.TeamProject] = '<project name>'" --org <organization URL>  -o table`
4. No data is being provided in the 'Assigned To' column.

**Screenshot**
![Capture](https://user-images.githubusercontent.com/25266173/59922935-ab5f7d80-944f-11e9-8118-542296dc4ba4.PNG)

**Comment by atbagga** [comment]
Fix in 0.12.0. Release ETA Next week.
