### ISSUE TITLE
[Bug] Azure DevOps Extension is not pre-installed on hosted agents.

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#689]
**Describe the bug**
The azure devops extension shows to be preinstalled on the hosted agents and the pool information indicates this as well. However, on running a devops command directly, there is an error indicating that the devops commands are not part of the az module.

**To Reproduce**
1. Create a release pipeline task
2. Include an azure cli task

**Expected behavior**
Run az devops project list : Expect an error indicating that the user is not signed in.

**Comment by atbagga** [comment]
Related issue in image generation Repo - https://github.com/microsoft/azure-pipelines-image-generation/issues/1023

**Comment by atbagga** [comment]
Assigning to myself. 
I will take care of fixing the above linked issue.

**Comment by gauravsaralMs** [comment]
https://github.com/Azure/azure-cli/issues/9831
This is one of the possible ways to solve this issue

**Comment by gauravsaralMs** [comment]
This is fixed in code and will hopefully be rolled out soon

**Comment by kamil-mrzyglod** [comment]
Hey guys, is there an ETA for this?

**Comment by gauravsaralMs** [comment]
> Hey guys, is there an ETA for this?

Hi
we have rolled back the changes to enabled this... 
in the meantime you can still install devops extension just like any other extension.

can you share your scenario and issues with installing azure devops extension separately.

**Comment by kamil-mrzyglod** [comment]
@gauravsaralMs I'm able to install the extension, however, when I try to use it with Azure CLI tasks, I'm getting the following error:
```
ERROR: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
```
I can see in the logs, that `az login` command is run successfully:
```
Setting active cloud to: AzureCloud
[command]/usr/bin/az cloud set -n AzureCloud
[command]/usr/bin/az login --service-principal -u *** -p *** --tenant ***
[
  {
    "cloudName": "AzureCloud",
    "id": "",
    "isDefault": true,
    "name": "",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
```
And to be honest I'm stuck for now.

**Comment by gauravsaralMs** [comment]
@kamil-mrzyglod sorry to hear that.
right now service principal is not supported by azure devops
you will have to set PAT in environment variable.

pointer: https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/samples.md#log-in-via-azure-devops-personal-access-token-pat

cc: @snankani  @geverghe

**Comment by kamil-mrzyglod** [comment]
@gauravsaralMs  I see. Is a support for service principals something you are planning in the near future?

**Comment by timwebster9** [comment]
I'm having the same issue, but with Docker agents.  We've pre-installed the extension on the image we are using. We need to because the agent runs on AKS in a private VNET behind an Azure firewall, and we don't want to open it up to the various MS and AWS CDNs required to install the extension at runtime (aka.ms, s3, etc).

When you execute an Azure CLI task and look at the raw logs, the extension is definitely installed:

```
2019-09-14T10:35:25.0978479Z [command]/usr/bin/az --version
2019-09-14T10:35:25.6977462Z WARNING: Unable to check if your CLI is up-to-date. Check your internet connection.
2019-09-14T10:35:25.6977801Z azure-cli                         2.0.73
2019-09-14T10:35:25.6978347Z 
2019-09-14T10:35:25.6978714Z command-modules-nspkg               2.0.3
2019-09-14T10:35:25.6978785Z core                              2.0.73
2019-09-14T10:35:25.6978894Z nspkg                              3.0.4
2019-09-14T10:35:25.6979579Z telemetry                          1.0.3
2019-09-14T10:35:25.6979802Z 
2019-09-14T10:35:25.6979898Z Extensions:
2019-09-14T10:35:25.6980399Z azure-devops                      0.12.0
```
However when trying to execute an `az devops` command you get:

```
ERROR: az: 'devops' is not in the 'az' command group. See 'az --help'.
```

Also, the extension was installed at build time using the root user, and it's also running as the root user, so not sure what's going on here.  If you exec to the running container it works as well:

```
kubectl -n azure-pipelines-agent exec -it azure-pipelines-agent-cf79bbdb6-h55jw -- az devops -h

Group
    az devops : Manage Azure DevOps organization level operations.
        Related Groups
        az pipelines: Manage Azure Pipelines
        az boards: Manage Azure Boards
        az repos: Manage Azure Repos
        az artifacts: Manage Azure Artifacts.
        ...
```

Azure/azure-cli#9831 mentions a workaround, but it's not clear what that is. Can someone please elaborate?

**Comment by geverghe** [comment]
@gauravsaralMs - would you be able to help here?

**Comment by gauravsaralMs** [comment]
@timwebster9 : you will have to set Azure_Extension_Dir environment variable to a directory which will get packed (and also make sure Azure_Extension_dir  persists). Although it can be tricky because of permission issues.
Let me know how it goes

**Comment by gauravsaralMs** [comment]
Also we are also struggling with this in Linux images. Hence opened https://github.com/Azure/azure-cli/issues/9831

**Comment by timwebster9** [comment]
@gauravsaralMs just using `useGlobalConfig: true` in the Azure CLI task was enough for us at the moment.  But yes, perhaps I'll try that the next time I need to update the image.

**Comment by ashishonce** [comment]
@gauravsaralMs can we close this issue? Not sure about current state of this.

**Comment by gauravsaralMs** [comment]
@ashishonce : so last I remember (please confirm)
DevOps extension is now installed on windows hosted agents but not in Linux.

It will be better if present owners can take the call to close it in the current state or keep it open.

**Comment by gauravsaralMs** [comment]
Closing this issue because ADO CLI extension is now coming pre installed in Linux and Windows Image

Recommendation for Mac Image Users
- Run
`az config set extension.use_dynamic_install=yes_without_prompt`
before running any ADO CLI command and that will take care to install the ADO CLI extension silently in background.
