### ISSUE TITLE
[Feature Request] Prefill PR description with commit message

### ISSUE THREAD

**Issue by ralphhendriks** [Azure/azure-devops-cli-extension#695]
**Is your feature request related to a problem? Please describe.**
When I create a PR through the UI for a branch that contains only a single commit relative to the target, the description is set to the commit message. With the CLI Extension (`az repos pr create`) in the same situation the description remains empty.

**Describe the solution you'd like**
When creating a PR through the CLI Extension, ideally I would like the first line of the commit message to be taken as the PR title (already the case), and the third line onward set as the description. I could also live with the behavior in which the complete commit message is taken as the PR description (as is the case in the UI now).

**Additional context**
In my team we have the workflow where we try to squash related commits already on the client. We value well crafted commit messages in line with git recommendations, which provide a concise title (up till 50 chars on the first line) and a more detailed description (separated by a blank line from the title). When a PR is initiated from a pushed commit, it would save time when the PR description is already pre-set from the commit message.

**Comment by geverghe** [comment]
Thank you for the request and providing detailed context!

**Comment by AltarBeastiful** [comment]
Would it be enough to have the same behaviour as the `Add commit messages` button on the UI when there is multiple commits.
![image](https://user-images.githubusercontent.com/3317699/73863493-78cc8e80-4840-11ea-96dc-0a64e01f47a8.png)

Right now there's no option in cli to trigger this behaviour. And once the PR is created, the option is not proposed in the UI.
Would be awesome to just add a flag for this when creating my PR !

**Comment by ralphhendriks** [comment]
@AltarBeastiful I do not completely understand your message.

> Would it be enough to have the same behaviour as the `Add commit messages` button on the UI when there is multiple commits.

Was that sentence intended as a question, and if so, to whom? My original issue is related to no description being set when creating a PR for a branch with a single commit difference to the target.

Presently, in the UI the following happens:
1. Creating a PR for a source branch with a **single commit** difference to the target branch: The title gets preset with the first line of the single commit message. The description gets preset with the complete commit message.
2. Creating a PR for a source branch with **multiple commits** difference to the target branch: The title and description fields remain empty. By clicking the indicated _Add commit messages_ button the text of all commit messages is concatenated to the description.

Through the CLI the following happens:
1. Creating a PR for a source branch with a **single commit** difference to the target branch: The title is set to the first line of the single commit message. The description remains empty.
2. Creating a PR for a source branch with **multiple commits** difference to the target branch: The title is set to 'Merge _SOURCEBRANCH_ to refs/heads/_TARGETBRANCH_'.

My feature request was only about the single commit case through the CLI. In that case I would like the description being prefilled. I think that can safely be changed without breaking expectations about present behavior.

Your very valid remark is specifically about the multiple commits-case. You request for an additional command line option to concatenate all commit messages into the description field. That will also work for the single commit case, with the remark that a user then always has to pass an additional option for the CLI to behave in the same way as the UI. My take would be that it would be a valuable additions to have this option, but to let it be a no-op in case there is only a single commit. What would you think?

**Comment by ajryan** [comment]
I see help-wanted tag, I'm going to attempt implementing this.

**Comment by spaasis** [comment]
Ah, I see Azure is using an older version of the extensionÖ

`az-version`: 

```
azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

```

And these changes are in azure-devops v1.0.0.

Does anyone know when 1.0 should be landing into the cli?
