### ISSUE TITLE
[Bug] az devops logout is not working

### ISSUE THREAD

**Issue by hjlarrea** [Azure/azure-devops-cli-extension#705]
**Describe the bug**
`az devops logout` is not terminating my PAT established session (using `az devops login`)

**To Reproduce**
Azure Cli Version: 
`azure-cli                         2.0.67 *`

Azure-Devops extension version: 
`azure-devops                      0.11.0`

1. login using `az devops login --org <myOrganizationsURL>`
2. Run command `az devops project list` to obtain the projects under my organization
3. Logout using `az devops logout` to terminate any active sessions.
4. Receive a message indicating all sessions have been terminated.
5. Run command `az devops project list` to obtain the projects under my organization. I can still retrieve the list of projects even after the logout. 

**Expected behavior**
After executing `az devops logout` any other az devops command should fail indicating there are no active sessions.

**Screenshots**
N/A

**Debug logs**
N/A

**Additional context**
I'm running Azure CLI within WSL, Ubuntu 18.04

**Comment by ishitam8** [comment]
HI @hjlarrea  ,

If you want to log out of particular account you can try using  same command with -org param
`az devops logout --org <ORG_URL>`

This should explicitly log you out of that organization.
Meanwhile, i'll check why the `az devops logout`  command is not logging you out of all accounts

Can you share the debugs logs for the same [az devops logout --debug] ?

**Comment by hjlarrea** [comment]
I was collecting the evidence and just noticed the issue is not happening anymore. Thanks for checking!
