### ISSUE TITLE
[Feature Request] Create service connection with "az devops service-endpoint create" using certificate authentication

### ISSUE THREAD

**Issue by BrianTJackett** [Azure/azure-devops-cli-extension#709]
**Is your feature request related to a problem? Please describe.**
Not able to create a service endpoint (connection) that uses certificate authentication.  Only client secret (service principal key) is allowed.

**Describe the solution you'd like**
I would like the ability to create a service endpoint (connection) that uses certificate authentication.  Acceptable to reference certificate by either thumbprint (certificate store) or explicit file path.

ex. syntax
az devops service-endpoint create --authorization-scheme ServicePrincipal
                                                              --name <value>
                                                              --service-endpoint-type azurerm
                                                              --azure-rm-service-principal-id <value>
                                                              **--azure-rm-service-principal-thumbprint <thumbprint>**
                                                              --azure-rm-subscription-id <value>
                                                              --azure-rm-subscription-name "<value>"  
                                                              --organization <value>
                                                              --project <value>
                                                              --azure-rm-tenant-id <redacted>

**Additional context**

**Comment by gauravsaralMs** [comment]
This is supported in latest release hence closing this
Details:
https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops
