### ISSUE TITLE
Error when you choose to view or edit the yaml

### ISSUE THREAD

**Issue by squassina** [Azure/azure-devops-cli-extension#716]
## Describe the bug

**Command Name**
`az pipelines create
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
[WinError 1155] No application is associated with the specified file for this operation: 'C:\\Users\\risquass\\AppData\\Local\\Temp\\AzurePipelines_vo4buktu\\azure-pipelines.yml'
Traceback (most recent call last):
pip-install-qdpilz60\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 578, in execute
cli\core\commands\__init__.py, ln 636, in _run_jobs_serially
cli\core\commands\__init__.py, ln 627, in _run_job
...
OSError: [WinError 1155] No application is associated with the specified file for this operation: 'C:\\Users\\risquass\\AppData\\Local\\Temp\\AzurePipelines_vo4buktu\\azure-pipelines.yml'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az pipelines create --name {} --organization {} --project {} --repository {} --branch {}`
- choose to edit yaml file

## Expected Behavior
Open yaml file to be viewed/edited

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.69
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
azure-devops 0.11.0

```

**Comment by squassina** [comment]
This can be either closed or the yaml file could be opened in the default text editor.

When I opened the .yml file for the first time in Windows it asked which program I'd like to use to open the file. I selected Visual Studio Code and check the always open with this program. Now the command worked as expected.

**Comment by atbagga** [comment]
Will add a fallback to open the choose program dialog in case the default editor is not set for the file.
