### ISSUE TITLE
[Feature Request] az repos policy merge-strategy create --use-basic-merge --use-rebase-and-fast-forward --use-rebase-with-merge-commit

### ISSUE THREAD

**Issue by fdcds** [Azure/azure-devops-cli-extension#718]
**Is your feature request related to a problem? Please describe.**

The web UI of Azure DevOps allows to permit 4 merge strategies in repository branch policies:
* basic merge
* squash merge
* rebase and fast-forward
* rebase with merge commit

The azure-devops-cli-extension only supports configuring squash merges through `az repos policy merge-strategy create --use-squash-merge`.

**Describe the solution you'd like**

`az repos policy merge-strategy create` understands the additional arguments `--use-basic-merge`, `--use-rebase-and-fast-forward` and `--use-rebase-with-merge-commit`

**Comment by atbagga** [comment]
**How the API used to work. (This is how the command works today):** 
1. use-squash-merge is set to False:
![image](https://user-images.githubusercontent.com/11888714/64333261-d3449300-cff3-11e9-8150-587599961e5a.png)
1. use-squash-merge is set to True:
![image](https://user-images.githubusercontent.com/11888714/64333311-ebb4ad80-cff3-11e9-9c37-f1e741261c37.png)

**Suggested changes to command to work with newer merge types-** 
1. --use-squash-merge becomes a deprecated option to be removed in the future and keeps working as it does stated above.

1. Add 4 new merge policy options -

![image](https://user-images.githubusercontent.com/11888714/64333470-346c6680-cff4-11e9-973d-48238a10b4b2.png)

New command keeps working for older scripts as it used to. For newer use the command will list the option --use-squash-merge as deprecated. It will allow the users to use the newer merge options in any combination as required in both create and update command.

![image](https://user-images.githubusercontent.com/11888714/64332814-dc813000-cff2-11e9-8c5b-e3644ba6947e.png)

**Comment by fdcds** [comment]
Assuming this will be in version 0.13: Is there already an ETA for the release?

**Comment by atbagga** [comment]
@fdcds  Not yet but I will update it. Expect it in next couple of weeks.

**Comment by atbagga** [comment]
@fdcds Release got delayed for a bit, but the new version is out now. 
Give it a try and share any feedback if you have.

**Comment by fdcds** [comment]
> @fdcds Release got delayed for a bit, but the new version is out now.
> Give it a try and share any feedback if you have.

Appears to work. Thanks!
