### ISSUE TITLE
Use PowerShell variable in Query

### ISSUE THREAD

**Issue by azurekid** [Azure/azure-devops-cli-extension#734]
## Describe the bug

**Command Name**
`az devops project list
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
Expected 2 arguments for function contains(), received 3
Traceback (most recent call last):
pip-install-qdpilz60\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 590, in execute
pip-install-qdpilz60\knack\knack\cli.py, ln 162, in raise_event
pip-install-qdpilz60\knack\knack\query.py, ln 46, in filter_output
pip-install-qdpilz60\jmespath\jmespath\parser.py, ln 509, in search
...
pip-install-qdpilz60\jmespath\jmespath\functions.py, ln 80, in call_function
pip-install-qdpilz60\jmespath\jmespath\functions.py, ln 90, in _validate_arguments
jmespath.exceptions.ArityError: Expected 2 arguments for function contains(), received 3
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops project list --org {} --query {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.69

Extensions:
azure-devops 0.11.0

```

**Comment by azurekid** [comment]
az devops project list --org $endpoint --query "[?contains(name, $ProjectName)]"
The $projectName variable used in a query creates an error

**Comment by gauravsaralMs** [comment]
@azurekid : the string substitution looks incorrect.
"[?contains(name, '$($ProjectName)')]" is a string and you want to replace projectName using a variable so it should be string substition.
can you instead try
```bash
az devops project list --org $endpoint --query "[?contains(name, '$($ProjectName)')]"
```

**Comment by geverghe** [comment]
Closing this issue. Let us know in case it doesn't work.
