### ISSUE TITLE
[Feature Request] Allow queuing of pull request branches

### ISSUE THREAD

**Issue by hartez** [Azure/azure-devops-cli-extension#735]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to queue builds of a pull request branch. For example:
`az pipelines build queue --branch refs/pull/6948 --definition-id 7981`

Currently this command fails.

**Describe the solution you'd like**

I would like the command above to queue up a build of `refs/pull/6948`.

**Additional context**

It looks like `build.py` takes the `branch` parameter and checks whether it begins with `refs/head` (via the `resolve_git_ref_heads` function in `git.py`); if it does not, the prefix is added. So the command above ends up with a branch of `refs/head/refs/pull/6948`.

**Comment by atbagga** [comment]
@hartez Thank you for reporting this. 

Change is merged. Note that once the changes are release in version 0.12.0 pull request branches can be used for build the names for PR branches are generally like **refs/pull/<PR_ID>/merge** e.g. `refs/pull/1/merge`.

ETA of release by end of this week.

**Comment by hartez** [comment]
Fantastic - thank you!
I see the release for version 0.12.0 - when will that update be available via `az extension update`?

**Comment by atbagga** [comment]
As soon as this PR is merged - https://github.com/Azure/azure-cli-extensions/pull/882

**Comment by jogleasonjr** [comment]
Is it possible for this manually queued build to count towards the build policy of the pull request? For example, I can't merge PR number 123 until a build is queued from the UI. What I'm looking to do is call `az pipelines build queue "refs/pull/10122/123"` and have it indicate to the PR that its build is running, so an autocomplete PR will merge. 

Is this possible?

![image](https://user-images.githubusercontent.com/5757382/201367887-671eac48-b4ff-4533-89d9-c09bbe77a240.png)

**Comment by jwalton3141** [comment]
For **@[jogleasonjr](https://github.com/jogleasonjr)**, I came across the same issue / desire as you today.

I found that to queue a pipeline and have it count towards your PR's build validation pipeline, you instead want to use the `az repos pr policy queue`, rather than any of the `az pipelines` commands.

I added more detail to this StackOverflow answer [here](https://stackoverflow.com/a/77419508/11021886).
