### ISSUE TITLE
[Bug] Az devops login failing

### ISSUE THREAD

**Issue by paulpuvi06** [Azure/azure-devops-cli-extension#738]
**Describe the bug**

**az devops login**  failing after passing the token
Token:
The command failed with an unexpected error. Here is the traceback:

Can't store password on keychain
Traceback (most recent call last):
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
PasswordSetError: Can't store password on keychain

**To Reproduce**
Azure Cli Version: 

╰─ az -v
azure-cli                         2.0.70

command-modules-nspkg               2.0.3
core                              2.0.70
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.11.0

Python location '/Users/ppuvi/lib/azure-cli/bin/python'
Extensions directory '/Users/ppuvi/.azure/cliextensions'

Python (Darwin) 2.7.10 (default, Feb 22 2019, 21:55:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Azure-Devops extension version: 
azure-devops (0.11.0)

Error:
Can't store password on keychain
Traceback (most recent call last):
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
PasswordSetError: Can't store password on keychain

**Expected behavior**
it should login 

**Debug logs**
az devops login --debug
Command arguments: ['devops', 'login', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x10c87e6e0>, <function on_global_arguments at 0x10c9212a8>, <function on_global_arguments at 0x10c933f50>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.003 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.016 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.024 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.005 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.027 seconds.
Loaded module 'vm' in 0.014 seconds.
Loaded all modules in 0.250 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/Users/ppuvi/.azure/cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: '/Users/ppuvi/.azure/cliextensions'
Loaded extension 'azure-devops' in 0.033 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function init_command_file_logging at 0x10c9b7410>]
az_command_data_logger : command args: devops login --debug
metadata file logging enabled - writing logs to '/Users/ppuvi/.azure/commands'.
Event: CommandInvoker.OnPostCommandTableCreate [<function add_subscription_parameter at 0x10c049aa0>, <function add_ids_arguments at 0x10ca10d70>, <function add_cache_arguments at 0x10d8621b8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10dbd3398>]
Event: CommandInvoker.OnPostParseArgs [<function handle_output_argument at 0x10c921320>, <function handle_query_parameter at 0x10c935050>, <function parse_ids_arguments at 0x10d85df50>, <function handler at 0x10dcebb18>, <function post_parse_args at 0x10e502b90>]
Extensions directory: '/Users/ppuvi/.azure/cliextensions'
Extensions directory: '/Users/ppuvi/.azure/cliextensions'
az_command_data_logger : extension name: azure-devops
az_command_data_logger : extension version: 0.10.0
Token:
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.OS_X.Keyring (priority: 5)
Setting credential: azdevops-cli: default
handling generic error
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

_cli.azure.cli.core.util : Can't store password on keychain
Traceback (most recent call last):
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
PasswordSetError: Can't store password on keychain
Can't store password on keychain
Traceback (most recent call last):
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/ppuvi/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
PasswordSetError: Can't store password on keychain
cli.azure.cli.core.util :_
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
az_command_data_logger : exit code: 1
command ran in 21.951 seconds.

**Comment by ishitam8** [comment]
Hi @paulpuvi06  ,

I would need few more details to debug this further.
Can you share what is your OS version and keyring version installed on your system?
Also, did you run the command from virtualenv?

**Comment by paulpuvi06** [comment]
HI @ishitam8 

ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; 

No, i ran it from local machine only.

Yesterday, I have reinstalled and tried as well . But no luck,  still the same issue

azure-cli                         2.0.69 *

command-modules-nspkg               2.0.3
core                              2.0.69 *
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.11.0

Python location '/usr/local/Cellar/azure-cli/2.0.69/libexec/bin/python'
Extensions directory '/Users/paul/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by paulpuvi06** [comment]
Hi @ishitam8 

it works now. This is fixed after removing az cli keychain.
