### ISSUE TITLE
Accessing Azure KeyVault secrets from Azure Devops Pipeline is not working 

### ISSUE THREAD

**Issue by andyf1ynn** [Azure/azure-devops-cli-extension#767]
**Describe the bug**
When adding a Variable group with Azure KeyVault secrets the secret values are not available in release pipeline. When the pipeline is run an error is caused by the KV variable being empty.

**To Reproduce**
Create an Azure resource group
Create a Key Vault
Add a secret named "SqlAdminPassword" to the KeyVault which can be used as an Azure SQL Server admin password
Set key vault Access Policies to user, select "Get and List" from drop down
In Azure Devops create a new Repo named ARM-Templates, add a file for the SQL ARM template and the SQL parameters ARM template.
Create a new release pipeline and add azure resource group deployment task, select the correct Azure subscription from the drop down list, add the name of the resource group the SQL server is to belong to.
Add a pipeline artifact pointing to the ARM-Templates GitRepo, in the resource task, select the path for the SQL Template and the parameters Template.

in the box to override template parameters box add -administratorLoginPassword $(SqlAdminPassword)

Azure-Devops web portal

1. Run pipeline

**Expected behavior**
A SQL Server instance is deployed to the resource group which can be accessed using the Admin password stored in the KV

**Screenshots**

**Debug logs**
Add the output of the command running it with debug mode (--debug)

**Additional context**

**Comment by atbagga** [comment]
@andyf1ynn The repository is only to handle Azure DevOps CLI related work. 

I do not see the linking the Variable group part in your steps. Can you double check you did this.
![image](https://user-images.githubusercontent.com/11888714/63910902-17f58a80-ca46-11e9-81bc-c95a0dd0d91f.png)

If that does not solve your problem, feedback link in the below docs page would be a better place to report this issue.

More documentation on usage of variable groups is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic).
