### ISSUE TITLE
"How to Start" documentation to have a CI/CD process using Azure DevOps Extensions

### ISSUE THREAD

**Issue by israelcr** [Azure/azure-devops-cli-extension#768]
**Is your feature request related to a problem? Please describe.**
I was trying to use each command as:
Create a new project
Adding a Team.
Creating a Build pipeline
Creating a Build queue.
Creating a Run pipeline.

And each command is executed as separeted, It will be great to have a 
"How to Start" documentation, having step by step, to have this documentation.
have  a CI-CD using DevOps extensions.

**Describe the solution you'd like**
Document Step by Step to have a "How to Start" documentation to have  a CI/CD using DevOps extensions.

**Additional context**
Using the new github repository that will be created with the project.

**Comment by geverghe** [comment]
Is this the document you are looking for - [Create your first pipeline from CLI](https://docs.microsoft.com/azure/devops/pipelines/create-first-pipeline-cli?view=azure-devops)? Is the need around this being in the documentation pertaining to the Azure DevOps CLI documentation section as well?

**Comment by geverghe** [comment]
@israelcr assuming the said documentation suffices need and closing this issue. Feel free to reopen in case there are any action items here.

**Comment by israelcr** [comment]
Thank You for this information.
