### ISSUE TITLE
Az devops Project list : missing some project

### ISSUE THREAD

**Issue by mathieugravil** [Azure/azure-devops-cli-extension#777]
## Describe the bug
When i launch az devops project list --organization "https://dev.azure.com/myorg", there are somme project which are missing...
**Command Name**
`az devops project list
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops project list --organization {} -o {}`

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

Extensions:
azure-devops 0.12.0
aks-preview 0.4.13

```

**Comment by mathieugravil** [comment]
Just a precision : I am project administrator on project i didn't see via api/az cli. I see them on portal....

**Comment by gauravsaralMs** [comment]
@mathieugravil : can you please run the same command with `--debug` option and share the output?
output will contain call to the get project API and response coming from it, in case you are not comfortable sharing the output then please check 
1. If the API is making call to the organization which you are targeting?
2. Does the response contains the projects which you think are missing?

**Comment by mathieugravil** [comment]
@gauravsaralMs 
In fact, i launch get on http://dev.azure.com/muorg/_apis/projects and I get list of projects but some of them are missing (same behaviour than as com). I think it is a problem on azure devops api...

**Comment by gauravsaralMs** [comment]
@mathieugravil 
What is the count of projects in your org?  any similarity between the projects which are missing?
If possible can you share the debug log after scrubbing information which is confidential?

**Comment by mathieugravil** [comment]
Hello @gauravsaralMs 
I have in some old log some id of projet i can see in  http://dev.azure.com/muorg/_apis/projects. And when i tried to get detail on it (GET https://dev.azure.com/{organization}/_apis/projects/{projectId}?api-version=5.1), it works but there isomething strange:
"lastUpdateTime":"0001-01-01T00:00:00"
It seems it is link to my trouble see:https://stackoverflow.com/questions/56535333/azure-devops-projects-list-get-not-returning-a-project

**Comment by gauravsaralMs** [comment]
@mathieugravil : Yes that looks strange.
can you please open an issue at 
https://developercommunity.visualstudio.com/spaces/21/index.html

I understand this might sound weird but this repo is issues exclusive to CLI and this issue is coming from API, so https://developercommunity.visualstudio.com/spaces/21/index.html is a better place to open this issue.

**Comment by mathieugravil** [comment]
@gauravsaralMs  you right. I will close this issue and open in the link you sent me.
