### ISSUE TITLE
Cannot download artifacts from centos 7

### ISSUE THREAD

**Issue by michaelsogos** [Azure/azure-devops-cli-extension#790]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.72 *

Extensions:
azure-devops 0.12.0

```

**Comment by jotaylo** [comment]
It looks like the machine is missing some native dependencies needed by .NET Core to run in CentOS (.NET Core is needed by ArtifactTool, which is the tool that actually executes the artifacts universal commands in the Azure CLI). Please check this guide to check that everything required by .NET Core is installed: https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

**Comment by elbatk** [comment]
Going to close this one as @jotaylo responded with some good info and we haven't heard back. Please feel free to reach back out if you're still having issues.
