### ISSUE TITLE
[Bug] list-work-items results in "request failed: The request is invalid"

### ISSUE THREAD

**Issue by cyberfox1** [Azure/azure-devops-cli-extension#791]
az 2.0.72
azure-devops 0.12.0

When I run" az boards iteration team list-work-items --team "MYTEAM" --id "MYSPRINT"

It comes back with: request failed: The request is invalid

**Comment by mehtaishita8** [comment]
Hi, 

To list work items for a given iteration and given team, you will have to pass iteration ID and not name to get a work items for that iterations.
`az boards iteration team list-work-items --team "MYTEAM" --id "xxxxx-fea8-4cd8-9273-xxxxxxxx"`

You can get the list of iterations for a team by running following command and get the required ID for your iteration
`az boards iteration team list --team "MYTEAM" -o json --query "[?contains(name,'MYSPRINT')]"`

**Comment by ishitam8** [comment]
Hi @cyberfox1 ,

To list work items for a given iteration and given team, you will have to pass iteration ID and not name to get a work items for that iterations.
`az boards iteration team list-work-items --team "MYTEAM" --id "xxxxx-fea8-4cd8-9273-xxxxxxxx"`

You can get the list of iterations for a team by running following command and get the required ID for your iteration
`az boards iteration team list --team "MYTEAM" -o json --query "[?contains(name,'MYSPRINT')]"`

**Comment by geverghe** [comment]
I am assuming the above clarified your question. I am closing this one. Feel free to re-open the issue in case it is still not working for you @cyberfox1
