### ISSUE TITLE
Could not create repos in Azure CLI. Still failed with no authurized even if I have login and set the default org and project.

### ISSUE THREAD

**Issue by LiangMengdi** [Azure/azure-devops-cli-extension#793]
## Describe the bug

**Command Name**
`az repos create
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
The requested resource requires user authentication: https://dev.azure.com/{org}/{project}/_apis/git/repositories
Traceback (most recent call last):
pip-install-qdpilz60\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 578, in execute
cli\core\commands\__init__.py, ln 636, in _run_jobs_serially
cli\core\commands\__init__.py, ln 627, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
...
azure-devops\azext_devops\devops_sdk\client.py, ln 254, in _handle_error
    url=request.url))
azext_devops.devops_sdk.exceptions.AzureDevOpsAuthenticationError: The requested resource requires user authentication: https://dev.azure.com/{org}/{project}/_apis/git/repositories
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az repos create --name {} --org {} --project {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.69 *

Extensions:
azure-devops 0.11.0

```

**Comment by ishitam8** [comment]
Hi @LiangMengdi  ,

Looks like you don't have enough permissions to create a repo
Can you check if you have Create repository permission on the same project?

You can verify this by visiting your Project settings page.
- (1) Project Settings, (2) Repo, - Repositories (3) Git repositories.
- Type your user name in the search box on the left and check the permissions corresponding to "Create repository" on the right side
It should be **allow** for you to create repos.

Refer [this](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops#set-git-repository-permissions) for more details.

**Comment by atbagga** [comment]
@LiangMengdi Were you able to get out of this error?

1. Were you logged in when you tried the command - Use ```az login``` or ```az devops login```.
2. Please try some command which needs lesser permissions like ```az devops project list``` to rule out permission issue.

*Also please update the extension there is a newer version available.

Please open a new issue if the above does not resolve the issue for you.
