### ISSUE TITLE
Update vsts-docs with more examples of adding/removing permission  bits

### ISSUE THREAD

**Issue by ishitam8** [Azure/azure-devops-cli-extension#795]
The line Here, --allow-bit/--deny-bit could be a single permission bit or addition of multiple permission bits. is unclear. Do you just add the permission bits together to get the value you want?

e.g if you apply a value of 7 for Releasemanagement, would you be able to view, edit and delete releases?

Some examples would be really helpful

**Comment by geverghe** [comment]
Makes sense - could we add more examples to both https://docs.microsoft.com/en-us/azure/devops/cli/permissions?view=azure-devops and command help. We can also link the doc in the command help for users to learn more about permission help.
