### ISSUE TITLE
Error while running az devops login command 

### ISSUE THREAD

**Issue by saiprasanthrajavarapu** [Azure/azure-devops-cli-extension#797]
## Describe the bug

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
(1312, 'CredWrite', 'A specified logon session does not exist. It may already have been terminated')
Traceback (most recent call last):
azure-devops\win32ctypes\pywin32\pywintypes.py, ln 35, in pywin32error
    yield
azure-devops\win32ctypes\pywin32\win32cred.py, ln 37, in CredWrite
    _authentication._CredWrite(c_pcreds, 0)
win32ctypes\core\cffi\_authentication.py, ln 153, in _CredWrite
    dlls.advapi32.CredWriteW(Credential, Flags), u'CredWrite')
...
OSError: [WinError 1312] A specified logon session does not exist. It may already have been terminated


azure-devops\win32ctypes\pywin32\pywintypes.py, ln 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1312, 'CredWrite', 'A specified logon session does not exist. It may already have been terminated')
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login --organization {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.73

Extensions:
azure-devops 0.11.0

```

**Comment by matthiaslischka** [comment]
We face the exact same issue on nearly every deployment build.

**Comment by gauravsaralMs** [comment]
@saiprasanthrajavarapu  @matthiaslischka : This is an issue related to environment and we will need your help in debugging this.
can you try the mitigation steps provided at https://techcommunity.microsoft.com/t5/Ask-The-Performance-Team/Task-Scheduler-Error-8220-A-specified-logon-session-does-not/ba-p/375056 in the machine which is running into this issue?

**Comment by saiprasanthrajavarapu** [comment]
@gauravsaralMs  I followed the mitigation steps and the security policy exactly as it is mentioned in the documents 
![image](https://user-images.githubusercontent.com/20098916/67038574-4d813080-f0e5-11e9-91e1-c667a90778f5.png)

**Comment by gauravsaralMs** [comment]
@saiprasanthrajavarapu : Did it worked?

**Comment by saiprasanthrajavarapu** [comment]
@gauravsaralMs nope It didnot work

**Comment by david-winter-at** [comment]
@saiprasanthrajavarapu @gauravsaralMs: Had the same issue with the "A specified logon session does not exist" error on our build servers.

The policy was set correctly, but gave an important hint anyway: The credential manager. We now explicitly remove the stored Azure credentials using "cmdkey /delete" prior to the "az devops login" command which seems to solve the issue.

**Comment by atbagga** [comment]
@saiprasanthrajavarapu  Did  David's workaround help?

**Comment by atbagga** [comment]
Closing due to lack of response. If the issue persists please feel free to raise a new issue. 

Thanks.
