### ISSUE TITLE
[Feature Request] Document the use of AZURE_DEVOPS_EXT_GITHUB_PAT

### ISSUE THREAD

**Issue by ams0** [Azure/azure-devops-cli-extension#801]
the `az devops service-endpoint github create` command can be run non-interactively by setting a `AZURE_DEVOPS_EXT_GITHUB_PAT` environment variable, but it's not documented (only in code [here](https://github.com/Azure/azure-devops-cli-extension/blob/ae2d49831f11601e44b30257e9d23334638fd770/azure-devops/azext_devops/dev/common/const.py#L19)).

Please add a documentation to the command.

**Comment by geverghe** [comment]
@gauravsaralMs - isn't this done (code complete but yet to release)? Including link to [this](https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops) document in service connection create command help?

**Comment by geverghe** [comment]
@gauravsaralMs - further, if it is done, could  you expand scope to include the proposal mentioned in #698
