### ISSUE TITLE
[Bug] A potentially dangerous Request.Path value was detected from the client (:)

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-devops-cli-extension#806]
**Describe the bug**
I'm trying to download Maven package from artifacts with name "android-builds.dev:corp"

**To Reproduce**
Azure Cli Version: 
azure-cli (2.0.57)

Azure-Devops extension version: 
azure-devops (0.12.0)

1. login using az devops login
2. Run command.: az artifacts universal download --organization "https://dev.azure.com/xxx" --feed "android-loading-app" --name "android-builds.dev:corp" --version "1.10.10" --path .
3. See error:

> An error occurred on the service. A potentially dangerous Request.Path value was detected from the client (:).

**Expected behavior**
Package should be downloaded

**Comment by phil-hodgson** [comment]
The command you're using is only for [downloading "Universal Packages" packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops), and not for Maven packages.
To [download Maven packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#install-an-artifact-from-your-feed), use the mvn (or gradle) tools.

**Comment by elbatk** [comment]
Closing this as it looks like Phil gave a solid response and we haven't heard back :)
