### ISSUE TITLE
[Bug] When making Azure Devops Cli requests with a valid user

### ISSUE THREAD

**Issue by rol09003** [Azure/azure-devops-cli-extension#807]
**Describe the bug**
When making Azure Devops Cli requests with a valid user the system throws an invalid user response

**To Reproduce**
Azure Cli Version: 
Use az  2.0.74

Azure-Devops extension version: 
Use az --version
Look for something like-
Extensions:
azure-devops (0.12.0)

1. login using az login
2. setup defaults..
3. Run command....

**Expected behavior**
I am getting an error saying my user is not authorized to access the resource.

**Screenshots**
![image](https://user-images.githubusercontent.com/22596788/66002393-d9962580-e460-11e9-9e5c-ea13f099c027.png)

**Debug logs** -Yes I am using the correct project name, and org. I have replaced all sensative data with "<data description>"
----------------------------------------------------------------------------------------------------
Command arguments: ['devops', 'security', 'group', 'list', '--org', 'https://dev.azure.com/<org name>’, '--project', <project name>', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fcd82fb1d08>, <function OutputProducer.on_global_arguments at 0x7fcd82adbb70>, <function CLIQuery.on_global_arguments at 0x7fcd82b05bf8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.016 seconds.
Loaded module 'acs' in 0.005 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.004 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.002 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.027 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.003 seconds.
Loaded module 'dls' in 0.002 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.004 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.002 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.004 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.019 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.003 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.005 seconds.
Loaded module 'role' in 0.003 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.003 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.005 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.021 seconds.
Loaded module 'vm' in 0.011 seconds.
Loaded all modules in 0.219 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/<username>/.azure/cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: '/home//<username>/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.74 min_required=2.0.49 max_required=None
Extensions directory: '/home//<username>/.azure/cliextensions'
Loaded extension 'azure-devops' in 0.019 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fcd8287ff28>]
az_command_data_logger : command args: devops security group list --org {} --project {} --debug
metadata file logging enabled - writing logs to '/home//<username>/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fcd82820f28>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fcd827d7950>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fcd827d7ae8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fcd8032d378>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fcd82adbbf8>, <function CLIQuery.handle_query_parameter at 0x7fcd82b05c80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fcd827d79d8>, <function handler at 0x7fcd801f6400>, <function DevCommandsLoader.post_parse_args at 0x7fcd7f9e2488>]
Extensions directory: '/home//<username>/.azure/cliextensions'
Extensions directory: '/home//<username>/.azure/cliextensions'
az_command_data_logger : extension name: azure-devops
az_command_data_logger : extension version: 0.12.0
Getting credential: azdevops-cli:https://dev.azure.com/<org name>
Getting credential: azdevops-cli: default
Current cloud config:
AzureCloud
trying to get token (temp) for tenant <tenant number> and user <AZ devops username>
attempting to read file /home//<username>/.azure/accessTokens.json as utf-8-sig
adal-python : <guid> - Authority:Performing instance discovery: ...
adal-python : <guid> - Authority:Performing static instance discovery
adal-python : <guid> - Authority:Authority validated via static instance discovery
adal-python : <guid> - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : <guid> - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : <guid>- CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : <guid>- CacheDriver:Found 7 potential entries.
adal-python : <guid>- CacheDriver:Resource specific token found.
adal-python : <guid>- CacheDriver:Returning token from cache lookup, AccessTokenId: <token>', RefreshTokenId: <refresh token>'
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Current cloud config:
AzureCloud
Azure devops telemetry enabled.
Logging telemetry to azure devops server.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache : Cache file does not exist: /home/mike/.azure-devops/python-sdk/cache/options.json
azext_devops.devops_sdk._file_cache : Cache file does not exist: /home/mike/.azure-devops/python-sdk/cache/resources.json
azext_devops.devops_sdk.connection : File cache miss for resources on: https://dev.azure.com/<org name>
azext_devops.devops_sdk.client : File cache miss for options on: https://dev.azure.com/<org name>
azext_devops.devops_sdk.client : File cache miss for options on: https://dev.azure.com/<org name>
azext_devops.devops_sdk.client : OPTIONS https://dev.azure.com/<org name>/_apis
azext_devops.devops_sdk.client : OPTIONS https://dev.azure.com/<org name>/_apis
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): dev.azure.com:443
urllib3.connectionpool : Starting new HTTPS connection (1): dev.azure.com:443
urllib3.connectionpool : https://dev.azure.com:<port> "OPTIONS /<org name>/_apis HTTP/1.1" <guid>
azext_devops.devops_sdk.client : Response content: b'{"$id":"1","innerException":null,"message":"TF400813: The user \’<userID>\\\\<AZ username>\' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}'
msrest.exceptions : TF400813: The user ‘<userID>\\\\<AZ username>' is not authorized to access this resource.
TF400813: The user ’<userID>\\\\<AZ username>' is not authorized to access this resource.
Traceback (most recent call last):
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/dev/common/telemetry.py", line 92, in _send_tracking_ci_event
    ci_client.publish_events([vsts_tracking_data])
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/v5_0/customer_intelligence/customer_intelligence_client.py", line 23, in publish_events
    content=content)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 63, in _send
    query_parameters=query_parameters)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 105, in _create_request_message
    location = self._get_resource_location(location_id)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 135, in _get_resource_location
    Client._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 171, in _get_resource_locations
    response = self._send_request(request, headers=headers)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "/home/<username>/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 233, in _handle_error
    raise AzureDevOpsServiceError(wrapped_exception)
azext_devops.devops_sdk.exceptions.AzureDevOpsServiceError: TF400813: The user '<userID>\\\\<AZ username>' is not authorized to access this resource.
urllib3.connectionpool : https://dev.azure.com:<port> "OPTIONS /<org name>/_apis HTTP/1.1" <guid>
azext_devops.devops_sdk.client : Response content: b'{"$id":"1","innerException":null,"message":"TF400813: The user \’<userID>\\\\<AZ username>\' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}'
msrest.exceptions : TF400813: The user ’<userID>\\\\<AZ username>' is not authorized to access this resource.
handling vsts service error
cli.azure.cli.core.util : TF400813: The user ’<userID>\\\\<AZ username>' is not authorized to access this resource.
TF400813: The user ’<userID>\\\\<AZ username>' is not authorized to access this resource.
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2578 in cache
telemetry.check : Negative: The /home/<username>/.azure/telemetry.txt was modified at 2019-10-01 <Ip address>, which in less than 600.000000 s
command ran in 1.830 seconds.

-----------------------------------------------------------------------------------------------------

**Additional context**
It's just a simple get command, that was working a day ago.

**Comment by rol09003** [comment]
I have resolved the issue locally using a different PAT from a different user. However this user has owner level access, and it's still not working for that user.

**Comment by geverghe** [comment]
@rol09003 - this looks to be a permission issue and not specific to the CLI as such. Could you confirm by trying the same from the UI as well?

**Comment by icloudmegam** [comment]
try "powercfg –restoredefaultschemes" to reset the cmd and after that try login again it worked for me.
