### ISSUE TITLE
[Bug] az devops user add with license type earlyAdopter fails

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/azure-devops-cli-extension#810]
**Describe the bug**
if I run `az devops user add --email-id $email --license-type earlyAdopter --organization $organization --send-email-invite false` the cli fails with error 'A user cannot be assigned an Account-EarlyAdopter license.'

but if I run the same command with license type stakeholder, the user is added with earlyAdopter license.

**To Reproduce**
Azure Cli Version: 2.0.72
Use az --version 
Look for something like-
azure-cli (2.0.55)

Azure-Devops extension version: 0.12.0
Use az --version
Look for something like-
Extensions:
azure-devops (0.12.0)

1. login using az login
2. setup defaults..
3. Run command....

**Expected behavior**
Early adopter flag works as expected.

**Screenshots**

**Debug logs**
Add the output of the command running it with debug mode (--debug)

**Additional context**

**Comment by geverghe** [comment]
Thank you for reporting this issue @rguthriemsft . @ishitam8 would you be able to help here?

**Comment by ishitam8** [comment]
Hi @rguthriemsft ,

All @microsoft.com accounts are automatically given earlyAdopter license-type. So, if you want to add a new user, you can try adding with license type **express** or **stakeholder**, and if that user has valid msdn subscription it would be automatically assigned to earlyAdopter license.

**Comment by atbagga** [comment]
@rguthriemsft  
Please see the explanation as per above comment. Early Adopter is an internal thing which is not exposed via API it is auto detected in the backend for appropriate internal users.

Closing the issue,  please open a new one if you need to.
