### ISSUE TITLE
[Feature Request] Set pipeline's variable groups and triggers

### ISSUE THREAD

**Issue by sho-yamashita** [Azure/azure-devops-cli-extension#812]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set pipeline's variable groups and triggers using CLI.

**Describe the solution you'd like**
```
# set pipeline's variable groups
az pipelines set variable-groups --id ${PIPELINE_ID} \
　--name ${VARIABLE_GROUPS_NAME} 
    ・
    ・
    ・
```
```
# set pipeline's triggers(continuous integration)
az pipelines set triggers ci --id ${PIPELINE_ID} \
    --override-the-yml-ci-trigger-from-here true
    --enable-ci true \
    ・
    ・
    ・
# set pipeline's triggers(pull request)
az pipelines set triggers pr --id ${PIPELINE_ID} \
    --override-the-yml-ci-trigger-from-here true
    --enable-pr true \
    ・
    ・
    ・
# set pipeline's triggers(scheduled)
az pipelines set triggers scheduled --id=${PIPELINE_ID} \
    --when-to-build mon
    ・
    ・
    ・
```

I would appreciate your kind consideration.

**Comment by atbagga** [comment]
@sho-yamashita Azure pipelines[ variable groups ](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group)and [triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#ci-triggers) should reside in the yaml file. 

Please let me know if this does not help you accomplish your use case.

**Comment by sho-yamashita** [comment]
@atbagga 
I thought that variable groups and triggers can only be set after pipeline generation.
I think I can do it with the method you told me.
I'll try it. Thank you.

**Comment by sho-yamashita** [comment]
@atbagga 
I tried to set variable groups and triggers dynamically, but it didn't work.

like this.
```
variables:
- group: ${variableGroupName}

trigger:
  batch: true 
  branches:
    include:
    - ${Build.SourceBranchName}
pr: none 

```
Setting dynamic variable groups and triggers was not supported.

I want to change a variable group or a branch that triggers it using the same yml file in different pipelines
I would prefer to be able to configure variable groups and triggers on a pipeline using the CLI.

**Reference**
`Note: you cannot use variables in triggers, as variables are evaluated at runtime (after the trigger has fired).`
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

Dynamic Variable Groups?
https://github.com/MicrosoftDocs/vsts-docs/issues/3702

**Comment by atbagga** [comment]
@sho-yamashita Dynamic Variable-Group and Triggers is not supported as you pointed the issue itself. Since the eventual goal for pipelines is to put everything in the yaml rather than as pipeline metadata on the server, this enhancement to put these params in the command might not get prioritized as it will break sooner or later.

I had written a util script to do so for variable-groups which you can use. Checkout the script here - https://github.com/atbagga/PsSamples/tree/master/DevopsVarGroup

You can probably do something similar for setting up dynamic triggers.

Let me know if this is helpful.

**Comment by sho-yamashita** [comment]
@atbagga 
Thank you for creating the script.

I didn't know this command.
`az devops invoke --http-method PUT --area build・・・`

I think I can achieve my goal with your script.
Thank you.
