### ISSUE TITLE
[Feature Request] service-endpoint create needs option to specify pipeline policies

### ISSUE THREAD

**Issue by jfpanisset** [Azure/azure-devops-cli-extension#817]
When you create a service connection via the GUI, you get a check box to specific "Allow all pipelines to use this connection". This causes not only a POST connection to be sent to the `_apis/serviceendpoint/endpoints` REST API, but also a PATCH request to `_apis/build/authorizedresources` containing:

```
[{"authorized":true,"id":"the-resource-id","name":"the-resource-name","type":"endpoint"}]
```

If instead you use the CLI to create a service connection using:

```
az devops service-endpoint create ----service-endpoint-configuration foo.json
```

the PATCH request is not sent, and by default the service connection cannot be accessed by the pipeline until you enable that manually in the GUI. There may be a way to manipulate this permission using the az CLI (and if there is I'd love to know about it), it would be very convenience to add a command line option named something like `--all-pipelines-use` which would default the access to the service connection to all pipelines in the project. Even better would be explicit CLI support to manipulate access from specific pipelines if required.

**Comment by atbagga** [comment]
The policy cannot be at pipeline level since that is not supported. It is either all pipelines or none.

Till the command is enhanced to support the option you can use this command to change that setting from the CLI (complete your automation flow).

```az devops invoke --http-method patch --area build --resource authorizedresources --debug --route-parameters project=atbagga --api-version 5.0-preview --in-file .\a.txt --encoding ascii```

Where a.txt will contain the json that you mentioned in the issue. 

```[{"authorized":true,"id":"the-resource-id","name":"the-resource-name","type":"endpoint"}]```

**Comment by jfpanisset** [comment]
Thank you very much, `az devops invoke` seems to work and correctly sets the "Allow all pipelines to use this service connection" property for my newly created Docker Hub service connection. Before I got your answer I was trying to use `az rest --method patch ...` but wasn't getting anywhere.

Until 'az devops service-endpoint create` can be enhanced with this functionality, would it make sense to add this recommendation to the documentation?

**Comment by geverghe** [comment]
Can we investigate what it means to enable this in the command? @jfpanisset - Feel free to chime in based on your expectation. 
### 1.  `az devops service-endpoint create --enable-for-all`
Input - service end point name and other required inputs based on service endpoint type
Output - json output of the create service endpoint connection, 
Advantages 
1. One command to achieve objective

Drawback
1. Cannot understand what happened to the status of enable for all; did it successfully happen? was there an error? 
[Potentially follow up with the team to include this detail in the json output to understand status]
2. What if I want to enforce the policy to an existing pipeline - can't create again.

### 2.  `az devops service-endpoint create` followed by `az devops service-endpoint enable-for-all`
Advantages
1. Modular and therefore available for even existing pipelines
2. Each command corresponds to an API and therefore JSON outputs are reflective of the actions undertaken.

### 3. `az devops service-endpoint create --enable-for-all` and `az devops service-endpoint enable-for-all`
Advantages
1. Available as both a command and as a parameter enabling users to avoid two separate commands when creating a service connection.
2. The separate command allows users to execute the same for existing service connections.

Disadvantages:
1. Cannot understand what happened to the status of enable for all when bundled with create; did it successfully happen? was there an error? 
[Potentially follow up with the team to include this detail in the json output to understand status]

My proposal would be Option 2 as the starting point and evaluate if 3 is possible by checking if the current API has this policy enforcement data in the API output and if not whether it is possible to get it included in the data.

**Comment by atbagga** [comment]
@geverghe we already handle this is variable-groups.
Check create and update commands - - authorize parameter is what we use. 

So we have taken approach 1 in that case. 

Drawbacks are not applicable there... 
Status of authorize is appended to the output and you can manipulate it using update command.

**Comment by geverghe** [comment]
That's awesome! However, I see that we have not enabled update service endpoint. So then, this would involve a few command updates and potentially new commands across all service end point command groups

Command updates
### az devops service-endpoint create --enable-for-all
### az devops service-endpoint github create --enable-for-all
### az devops service-endpoint azurerm create --enable-for-all

New commands
### az devops service-endpoint update --enable-for-all
### az devops service-endpoint github update --enable-for-all
### az devops service-endpoint azurerm update --enable-for-all

**Comment by jfpanisset** [comment]
Interestingly I've been using `az devops service-endpoint github create` followed by `az pipelines create ... --service-connection` and have not had any authorization errors with the created pipeline having access to the GitHub service connection, even though I haven't made any explicit calls to manipulate its permissions. In the AZ DevOps UI it shows up as having "Authorized Pipelines" set to the pipeline I created, so it seems the act of creating a pipeline and setting its --service-connection is in fact authorizing that service connection?

I don't have a strong opinion on the exact syntax to be used to authorize service connections, as long as it is well documented: whatever makes the most sense from an implementation and maintainability point of view.

In order to expose all of the GUI options to the CLI, would it make sense to also support options to authorize service connections only for certain pipelines in the project? For instance if I have separate pipelines for "build" and "push packages to a registry", it would make sense to only have the service connection authorized for the "push packages to a registry" pipeline.

**Comment by atbagga** [comment]
@jfpanisset I am not exactly sure of this.. but this is a probable explanation of the behavior you see.

When you are the owner of the service connection and you execute the first run of the pipeline that service connection is authorized to be used by the pipeline implicitly. 

Problem happens when you try to use someone else's service connection in your pipeline. The pipeline run will fail until either that service connection is marked to be authorized for all pipelines OR the owner of the service connection authorizes this one pipeline to be authorized by triggering the first run. 

Using APIs this functionality of authorizing only a single pipeline for using a service connection is not exposed.

**Comment by atbagga** [comment]
@geverghe Would it be good enough to just have one command - ```az devops service-endpoint update --enable-for-all``` for now.

It will be two steps for all users but that way we do not break compat by changing json response of non preview commands.

**Comment by geverghe** [comment]
Got it - makes sense.

**Comment by atbagga** [comment]
Fixed in version 0.16.0.
ETA for release end of this week.

**Comment by jfpanisset** [comment]
I can confirm that:

az devops service-endpoint update --id $DOCKER_CONNECTION_ID --enable-for-all

correctly sets the "Grant access permission to all pipelines" property for my recently created Docker Hub service connection, and I no longer need to use "az devops invoke --http-method patch ...". 

Thank you very much!

**Comment by manu-kanwarpal** [comment]
Hi Team,

I'm also facing this issue and the suggested workaround doesn't seem to work. Here's the error I get when I try it:

Starting: Update endpoint
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
az devops service-endpoint update --id $DOCKER_CONNECTION_ID --enable-for-all
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/f6cb7b4a-8332-4eb1-8a20-639a0e142ec3.sh
ERROR: argument --id: expected one argument

TRY THIS:
https://aka.ms/cli_ref
Read more about the command in reference docs
##[error]Bash exited with code '2'.
Finishing: Update endpoint

**Comment by gauravsaralMs** [comment]
@manu-kanwarpal 
- are you sure that `$DOCKER_CONNECTION_ID` has some value
- have you tried running the command locally, if it is working locally and not in your pipeline then that is an issue with your pipeline and not azure devops cli
- can you add `--debug` to the command and then share the output

**Comment by manu-kanwarpal** [comment]
Hi @gauravsaralMs 

Thanks for the prompt response. I don't think $DOCKER_CONNECTION_ID has a value, but I used it because that was the workaround suggested here. I also tried $GITHUB_CONNECTION_ID as I'm creating a Github service connection.

Here's the result of --debug.

I can try locally, but I'm using a simple bash step in Azure DevOps pipelines and this is a part of the same product group I imagine.

Cheers,
Manu

**Comment by gauravsaralMs** [comment]
> don't think $DOCKER_CONNECTION_ID has a value, but I used it because that was the workaround suggested here

Please spend some more time going through issue and suggestions

>I can try locally, but I'm using a simple bash step in Azure DevOps pipelines and this is a part of the same product group I imagine.

@manu-kanwarpal : I will highly recommend to try it first locally.

You should try to break your problem and solve it step by step
1. Articulate your problem clearly
2. Write bash script locally to solve your problem
    please read [documentation](https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20devops?view=azure-cli-latest) of CLI as and when needed
3. Run your bash script in ADO pipeline

**Comment by manu-kanwarpal** [comment]
Hi @gauravsaralMs 

1. The problem statement is that when I create a new service-endpoint for Git, I'd like to specify the pipeline policy such that --enable-for-all is also set at the time of creation. This is exactly what the original thread is about. It looks like this suggestion was not implemented and the suggested workaround was to run the following command after creating the service endpoint: 

az devops service-endpoint update --id $DOCKER_CONNECTION_ID --enable-for-all

When I run this, I get the errors I have shared above, because as far as I can tell $DOCKER_CONNECTION_ID doesn't have any value. 

2. I just tried to run a bash script locally and I see the same issue, $DOCKER_CONNECTION_ID doesn't have any value
3. The bash script is not running locally, so no point in running it in ADO as I was running the exact same steps there already.

I'd appreciate if you can test this at your end and see if it works for you.

Cheers,
Manu

**Comment by gauravsaralMs** [comment]
@manu-kanwarpal 

>az devops service-endpoint update --id $DOCKER_CONNECTION_ID --enable-for-all

here $DOCKER_CONNECTION_ID is the variable for passing service endpoint ID 

see documentation of this command for more details
https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest#az_devops_service_endpoint_update

I tested this locally (not using bash script or ADO pipeline) and it is working fine for me
