### ISSUE TITLE
[Bug] az artifacts universal download throws System.TypeInitializationException during docker image build

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#826]
Issue reference from Azure CLI Extension repo
https://github.com/Azure/azure-cli-extensions/issues/934

**Comment by migolfi** [comment]
Hi, 
Has there been progress on this?
I'm trying to install the extension in a Docker container with the Azure CLI.
Thank you,
Michael

**Comment by omokoh** [comment]
Closing this issue as has been stale for long.
Please feel free to open is again , in-case required.
