### ISSUE TITLE
[Bug] Cannot download universal package

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#829]
Reference from Azure CLI extension repo:
https://github.com/Azure/azure-cli-extensions/issues/730

**Comment by shubham90** [comment]
I was not able to repro the bug in the latest versions of azure devops extension. Please update the client the extension. Can you also provide us the debug logs for us to be able to repro it? 

I'm closing this as no-repro- Please feel free to reopen it if this is still happening on latest versions of extension. Thanks!
