### ISSUE TITLE
[Bug] VM Developer image Artifact download

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#831]
Referencing issue from Azure CLI extension repo
https://github.com/Azure/azure-cli-extensions/issues/679

**Comment by shubham90** [comment]
I was not able to repro the bug in the latest release of azure-devops extension. Please update the extension and the az-cli tool and provide the debug logs for us to be able to repro it. 
I will close this bug as no-repro. But feel free to re-open it if this is still happening. Thanks!
