### ISSUE TITLE
[Bug] Universal Package Version Wildcard doesn't support SemVer 2.0 meta information

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [Azure/azure-devops-cli-extension#852]
**Describe the bug**
It is possible to create a universal artifact with SemVer 2.0 meta information and pre-release versions. It is not possible to wildcard these versions using the download command

**To Reproduce**
Azure Cli Version: 2.0.75
Azure-Devops extension version: 0.13.0

1. login using az login (with AZURE_DEVOPS_EXT_PAT because of issues with MFA)
2.Run the command
```ps
az artifacts universal publish --organization "myorg here" --feed "test-feeds" --name "my-package-name" --version "12.2.0-alpha1" --description "This is a semver 2.0 compliant version" --path M:\EXTERNAL\Lib32\
```
which works just fine.
4. Then run the command
```ps
az artifacts universal download --organization "https://dev.azure.com/horibatestautomation/" --feed "test-feeds" --name "my-package-name" --version "12.2.*" --path $env:TEMP
```
which returns the error
**Did not find any versions of 'my-package-name' that matched the pattern '12.2.*'**
**Expected behavior**
I would expect this to work since I can upload a pre-release version.
5. Then run the command
```ps
az artifacts universal download --organization "my organisation" --feed "test-feeds" --name "my-package-name" --version "12.2.*-*" --path $env:TEMP
```
which returns the error
**Invalid wildcard version pattern: Pre-release versions are not currently supported in wildcard patterns**
**Expected behavior**
I would expect this to work since I can upload a pre-release version.
6. Then run the command
```ps
az artifacts universal download --organization "my organisation" --feed "test-feeds" --name "my-package-name" --version "*" --path $env:TEMP
```
which returns the error
**Did not find any versions of 'my-package-name' that matched the pattern '*'**
**Expected behavior**
I would expect this to work since I can upload a pre-release version.
6. Explicitly using the full version used during upload downloads successfully
**Additional context**
Pre-release information should be supported in download if it is possible to supply it in the upload. Since I am writing some scaffolding code to fetch a large list of artifacts and I effectively want the latest version I need to wildcard to ignore the meta information and the revision version.
I think this issue has been kicking around for a while but I think asymmetric support of versions between upload/download will be an issue for others too.

**Comment by samuelkoppes** [comment]
Thank you for your feature request, we have taken this request into our backlog and will prioritize as resources become available.

**Comment by hansmbakker** [comment]
I reported this on https://developercommunity.visualstudio.com/t/Support-wildcards-for-prereleases-when-i/1645572
Please upvote!
