### ISSUE TITLE
[Feature Request] az artifacts universal should have option to list artifacts

### ISSUE THREAD

**Issue by praveen-pk** [Azure/azure-devops-cli-extension#856]
**Is your feature request related to a problem? Please describe.**
There seems to be no easy way to list universal artifacts in a feed. Please add this functionality to the devops extension.

**Describe the solution you'd like**
```
az artifacts universal  list --feed "<feed_name>" --version "*" --path "x/y/z"
```
The above command would list latest version of artifacts in "feed_name" at path "x/y/z"

**Comment by cpyfferoen** [comment]
You can list them thru the Web API - but you can't download
You can download them thru this extensions - but you can list them
Seems neither use case is actually useful... you'd have to combine them.

**Comment by A30004028** [comment]
To get this straight, we are able to download a package using `az artifacts universal` but we have no way of knowing about the existence of that package prior to this using the az cli tool.

**Comment by JvDrunen** [comment]
Any update?

**Comment by samuelkoppes** [comment]
Thank you for sharing your feature request. We have taken this into our backlog for consideration. Unfortunately we cannot provide a timeline at this time, but we will consider this request as resources become available in the future.

**Comment by ggirard07** [comment]
@samuelkoppes seriously?!?

How do you expect a package system to be widely used in the field without having the option to list available packages?
Can you point me to any package system out there not offering this option?

I understand that the original request here is perhaps a bit complicated to implement.
But a more simpler version, without all the options mentioned by @praveen-pk, [surfacing only the original Rest API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20packages?view=azure-devops-rest-6.0) is probably a low-hanging fruit you can integrate without much effort.
It will at least allows users having only the CLI to work more easily with the universal package product.

**Comment by JvDrunen** [comment]
Any update? this would be a very hand feature.

**Comment by r-k-b** [comment]
Found a similar suggestion in "Developer Community": https://developercommunity.visualstudio.com/t/Please-add-list-to-az-artifacts-unive/570784?ftype=idea&q=cli+list+universal+package+versions
