### ISSUE TITLE
[Bug] Unable to Create a release pipeline using az pipelines cli.

### ISSUE THREAD

**Issue by chaitanyagm** [Azure/azure-devops-cli-extension#866]
Unable to Create a release pipeline using az pipelines cli.

Is there a way to Create and start a release pipeline from cli itself without using the gui ??

**Comment by geverghe** [comment]
A  create is equivalent to kicking off a new release for an existing release pipeline. Even in the UI it says "Create release". Give` az pipelines release create` a shot. Feel free to reopen in case the clarification is not clear.

**Comment by geverghe** [comment]
For the initial part of the question - can you create a release definition/pipeline? Sadly no - you can only view and see the details of a release definition. Feel free to create a feature request and we will prioritize it as per bandwidth.

**Comment by chaitanyagm** [comment]
Hi George,
Thanks for the quick response.

I'm actually trying to automate the entire Pipeline Build & Release process. I was successful in Automating the "Build" using "az pipelines create". 

But "Release" is not straight forward. Is there a way to automate the entire Build & Release ?

Thanks

**Comment by atbagga** [comment]
@chaitanyagm  Right now there is no way to automate the creation of classic release definition. You will need to create the definition and then you can Queue a Release run using az pipelines release create command. 

It is possible to automate the new [yaml pipeline definitions](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema) (this is what you are already doing for build using az pipelines create) which can constitute both build (CI) and [release (CD)](https://azure.microsoft.com/en-us/updates/unified-pipelines/).

**Comment by geverghe** [comment]
I am closing this issue as the query seems to be answered. However, feel free to raise a feature request issue for creating a release. The reactions/community engagement on the issue will help us prioritize the same.
