### ISSUE TITLE
[Feature Request] How do I create a release from command line based on a build id?

### ISSUE THREAD

**Issue by MaurGi** [Azure/azure-devops-cli-extension#872]
How do you specify a build to an az pipelines release create command? 
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/release?view=azure-cli-latest#ext-azure-devops-az-pipelines-release-create

I created a build with 
`az pipelines release create --definition-name "${release_definition_name}" --branch "${build_branch}" | jq '.id'`

now I want to kick off a release with that build ID

I can `az pipelines release create --definition-name` but how do I tell it to use the artifact from that build_id ?

Looked into the doc but could not find it: https://github.com/Azure/azure-devops-cli-extension/tree/master/doc

**Comment by atbagga** [comment]
The command az pipelines release create is based on [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-5.0#artifactmetadata) REST API.

The parameter --artifact-metadata-list documented in the command can be used to refer the Build definition and Run Id for the artifact to be consumed. e.g.  --artifact-metadata-list Fabirkam.CI=123
will consume artifacts produced by run number 123 of the Fabrikam.CI build definition.

Where you say you created artifacts by running az pipelines release create.. shouldn't it be az pipelines build queue?

**Comment by geverghe** [comment]
@MaurGi - I am closing this issue. Please feel free to reopen the issue in case you need additional clarification.
