### ISSUE TITLE
[New command] Command to cancel build pipeline

### ISSUE THREAD

**Issue by jopham-sage** [Azure/azure-devops-cli-extension#876]
Is there a command line to cancel build pipeline?  I know we can run the pipeline but I want to cancel it also.  Thanks

**Comment by geverghe** [comment]
@atbagga - do we have an api for this?

**Comment by jopham-sage** [comment]
@geverghe Hi am looking for Azure Dev Ops CLI command to cancel build pipeline.  There's a delete CLI command but I think that's deleting the build.   I haven't tried that command but I'll test and see.  Thanks.

**Comment by geverghe** [comment]
So there are two elements - there is a build definition delete and there is a build delete. I think this build delete corresponds to canceling the build run. You can potentially give it a shot with az devops invoke to run this api till we build a command

**Comment by geverghe** [comment]
Looks like delete, as the verb indicates, deletes the run and therefore stopping the run. However, I think your use case is just cancel. @atbagga is looking into the update API and will get back to you on the API that can be used via `invoke` till we build a full fledged command.

**Comment by atbagga** [comment]
@jopham-sage The API for cancelling the build is documented [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/update%20build?view=azure-devops-rest-5.1).

```
PATCH https://dev.azure.com/atbagga/atbagga/_apis/build/Builds/120
Request content: {'status': 'Cancelling'}
```

You can use the following command as a workaround for the time being until this issue is prioritised and we add a command in CLI for the same. 

```
az devops invoke --area build --resource builds --route-parameters buildId=120 project=atbagga --in-file D:/patch.txt  --http-method patch 
```
Content in patch.txt -
```
{'status': 'Cancelling'}
```

**Comment by dhilmathy** [comment]
@atbagga I would like to take up this.

I am planning to create a new `update` command. Something like `az pipelines build update --status Cancelling`. Your thoughts & comments?

**Comment by atbagga** [comment]
@dhilmathy  Sorry missed the update. If you are still up for it please share the detailed command signature and go ahead.

**Comment by dhilmathy** [comment]
@atbagga I am planning to introduce a new command called `cancel`. 

**Command signature**
```
Command
    az pipelines build cancel : Cancels if build is running.

Arguments
    --id      [Required] : ID of the build.
    --detect             : Automatically detect organization.  Allowed values: false, true.
    --open               : Open the build results page in your web browser.
    --org --organization : Azure DevOps organization URL. You can configure the default organization
                           using az devops configure -d organization=ORG_URL. Required if not
                           configured as default or picked up via git config. Example:
                           https://dev.azure.com/MyOrganizationName/.
    --project -p         : Name or ID of the project. You can configure the default project using az
                           devops configure -d project=NAME_OR_ID. Required if not configured as
                           default or picked up via git config.
```

Will submit a PR if above command seems fine for you. Thanks!

**Comment by atbagga** [comment]
@dhilmathy Sorry, I am not a maintainer in this repo anymore. 
Tagging the owners for attention.. @Azure/azure-devops-cli

**Comment by dsfrederic** [comment]
@dhilmathy what's the status of this new command? 

I would use this to find a workaround for this outstanding [feature request](https://developercommunity.visualstudio.com/idea/918698/need-deploy-latest-and-cancel-the-others-feature-i.html)

**Comment by dhilmathy** [comment]
> @dhilmathy what's the status of this new command? 
> 
> I would use this to find a workaround for this outstanding [feature request](https://developercommunity.visualstudio.com/idea/918698/need-deploy-latest-and-cancel-the-others-feature-i.html)

@dsfrederic, I'd created the command based on the proposal I'd made earlier. I am waiting for maintainers comment before raising PR.

**Comment by dsfrederic** [comment]
@atbagga @elbatk @mitsha-microsoft can any of you guys help us out?

**Comment by atbagga** [comment]
Thanks @dhilmathy for the PR. I see the project owners are added as PR reviewers.

**Comment by kasajian** [comment]
> @jopham-sage The API for cancelling the build is documented [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/update%20build?view=azure-devops-rest-5.1).
> 
> ```
> PATCH https://dev.azure.com/atbagga/atbagga/_apis/build/Builds/120
> Request content: {'status': 'Cancelling'}
> ```
> 
> You can use the following command as a workaround for the time being until this issue is prioritised and we add a command in CLI for the same.
> 
> ```
> az devops invoke --area build --resource builds --route-parameters buildId=120 project=atbagga --in-file D:/patch.txt  --http-method patch 
> ```
> 
> Content in patch.txt -
> 
> ```
> {'status': 'Cancelling'}
> ```
Had to fix the contents of the patch.txt file to make it valid json.  the single quotes changed double quotes.  After I did that, it worked:

```
{"status": "Cancelling"}
```
Also had to add `--org` parameter

**Comment by duanqn** [comment]
I just tried this command locally but it does not work as expected. The pipeline status is updated to "cancelling" but it does not cancel the jobs inside. The jobs are still running and taking up build agent machines. What's worse, after the pipeline status is updated to "cancelling", I cannot manually cancel them in the web UI.

@dhilmathy @atbagga  Can you confirm this behavior?

> @atbagga I am planning to introduce a new command called `cancel`.
> 
> **Command signature**
> 
> ```
> Command
>     az pipelines build cancel : Cancels if build is running.
> 
> Arguments
>     --id      [Required] : ID of the build.
>     --detect             : Automatically detect organization.  Allowed values: false, true.
>     --open               : Open the build results page in your web browser.
>     --org --organization : Azure DevOps organization URL. You can configure the default organization
>                            using az devops configure -d organization=ORG_URL. Required if not
>                            configured as default or picked up via git config. Example:
>                            https://dev.azure.com/MyOrganizationName/.
>     --project -p         : Name or ID of the project. You can configure the default project using az
>                            devops configure -d project=NAME_OR_ID. Required if not configured as
>                            default or picked up via git config.
> ```
> 
> Will submit a PR if above command seems fine for you. Thanks!
