### ISSUE TITLE
Improve security tokens documentation

### ISSUE THREAD

**Issue by ishitam8** [Azure/azure-devops-cli-extension#887]
Need more clarifications and formatting for security tokens related to iteration namespace

**Comment by geverghe** [comment]
Could you add more clarity?

**Comment by ishitam8** [comment]
> Could you add more clarity? Are there some areas where we need to specifically invest?

Since iteration is a hierarchical namespace with no project GUID, token explanation of the same is confusing. It needs to be more elaborate, that's all

**Comment by ishitam8** [comment]
PR tracked [here]( https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/520)

**Comment by ishitam8** [comment]
azure devops docs PR is merged and document is updated. Hence, closing this
