### ISSUE TITLE
[Feature Request] Allow to specify yml file from local pc while creating new pipelines

### ISSUE THREAD

**Issue by gintuoklis** [Azure/azure-devops-cli-extension#895]
**Is your feature request related to a problem? Please describe.**
I would like to create build pipelines for all repositories in my project. If i use az pipelines CLI, I still have to choose some options manually, and it's not possible to script the process

**Describe the solution you'd like**
Please add possibility to specify yaml file from my local drive and make entire process scriptable. 

Best Regards, 
Gintautas

**Comment by atbagga** [comment]
@gintuoklis There is already an option to specify the yaml from repository. 
You can checkin the yaml file and create a pipeline from the yaml by specifying the path in the repository.

Use the --yaml-path parameter in create pipeline command docs [here](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest#ext-azure-devops-az-pipelines-create).

Please update the issue if you still have any problems in creating the pipeline.

**Comment by gintuoklis** [comment]
Hey @atbagga, 
I did what you advised. Looped through all repos, added new file, committed, and pushed. Then used azure clie with  --yaml-path parameter.

**Comment by atbagga** [comment]
Looks like the issue is resolved. If you still have any concerns feel free to open a new issue.

Thanks
