### ISSUE TITLE
publishing and downloading artifacts from azure devops using the CLI on Redhat 7.4

### ISSUE THREAD

**Issue by jessie828** [Azure/azure-devops-cli-extension#903]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.15.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


_sigint_handler() takes exactly 1 argument (3 given)
Traceback (most recent call last):
  File "/scratch/nljhfl/azure_cli/lib/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/scratch/nljhfl/azure_cli/lib/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: _sigint_handler() takes exactly 1 argument (3 given)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
Python 2.7.11
Shell: bash

azure-cli 2.0.77

Extensions:
azure-devops 0.15.0
interactive 0.4.3

```

**Comment by atbagga** [comment]
@jessie828 

- Are you able to run other commands? try a simple one like ```az devops project list``` or ```az repos list```
- Please share a debug log trace for the ```az artifacts universal download``` command. You can do so by running the command with ```--debug ```

**Comment by jessie828** [comment]
Hi @atbagga 

I am able to run the two commands you propose.
I get the correct output with the projects I own inside azure devops

Also I have attached a log file of the command:
`az artifacts universal publish --organization https://sede-pt-ssw.visualstudio.com --feed test_feed --name test-feed-thing --version 1.0.0 --description "description" --path . --debug `
[azPublishLog.txt](https://github.com/Azure/azure-devops-cli-extension/files/3896888/azPublishLog.txt)

**Comment by jessie828** [comment]
Hi @atbagga 
It looks like moving to python 3.7 fixed this issue for me.
Can you make sure that the [installation instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest)  on the microsoft website get updated correctly?


Here it lists that it is possible to install and run this with Python 2.7.

Thanks.

**Comment by simonbMS** [comment]
I have the same issue running on Windows

**Comment by apluche** [comment]
Hi @simonbMS, as a workaround, could you update python to the newest version? Please let us know if this fixes your issue.

**Comment by simonbMS** [comment]
Yes, it fixed on my PC. I thing the installation of the Azure CLI should install the required version

**Comment by apluche** [comment]
@simonbMS glad to hear that you are unblocked. Could you create a new Feature Request issue in this repo with your suggestion? It makes it easier for us to track new features. I've put a work item on our backlog to fix the docs.
