### ISSUE TITLE
[Bug] 'az boards query' supports only flat queries

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-devops-cli-extension#911]
Original Issue: https://github.com/Azure/azure-cli-extensions/issues/1120#issue-529546784
Reported by: @ashamrai 

'az boards query' supports only flat queries. The tree and direct links are not supported. However, there is no any information on docs or command output. The command returns an empty answer for wiql with links.

**Comment by adegeo** [comment]
Please reopen this issue. It still outputs an empty result. Better yet, add support for non-flat queries.....
