### ISSUE TITLE
Unable to publish Universal package

### ISSUE THREAD

**Issue by sailesh89** [Azure/azure-devops-cli-extension#919]
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.16.0.`

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {}`

## Environment Summary
```
Windows-10-10.0.15063-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75 *

Extensions:
azure-devops 0.16.0

```

**Comment by shubham90** [comment]
@sailesh89 I see that you are using a windows box for this. Is this machine shared or is some other process also running universal package operations on this machine at the time you saw this?

The other process could be a virus scanner running on this folder. 

Just wanted to make sure that this is not a shared resource issue. Let me know if this makes sense.

**Comment by sailesh89** [comment]
Hi,

It seems like more of a authentication issue. I did login using az devops login command using PAT token and then did as artifact upload. It’s causing issue. But in a new console, after setting the PAT token in the Env($env:AZURE_DEVOPS_EXT_PAT ) variable and directly using az artifact upload works.  I’m not sure why it’s not working without setting the env variable.

Regards,
Sailesh
________________________________

**Comment by shubham90** [comment]
It shouldn't be an auth issue because the artifact tool download part is completed. It could happen that some other process interfered with the download and therefore, download failed. Later, when the package downloader called the tool, it failed because it couldn't find it. The error message in your logs is consistent with that.

In that other console, the download might have succeeded and hence you didn't see the issue. 

Did you see 'Access Denied' message before this log?

**Comment by shubham90** [comment]
This bug is tracked by #798 I will close this one as duplicate.
