### ISSUE TITLE
[build policy] Build policy cannot be set to expire build immediately when branch is updated

### ISSUE THREAD

**Issue by pietergheysens** [Azure/azure-devops-cli-extension#923]
When using the command `az repos policy build create` there's no option to expire the build immediately when the target branch has been updated. The valid-duration argument is required and must be defined in minutes. When set to 0, the build expiration is set to "Never" and there's no option for expiring the build immediately when the target branch has been updated. This option is available via the Web UI but not via az cli.

[Link to docs](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy/build?view=azure-cli-latest#ext-azure-devops-az-repos-policy-build-create)

**Comment by atbagga** [comment]
@pietergheysens The policy options on the webUI are restricted. 
I tried the same from CLI and here are my observations - 
1. If you try to set the policy with **queueOnSourceUpdateOnly: false** and validDuration = 0 the policy correctly takes it as expire immediately. 
1. If you try to set the policy with **queueOnSourceUpdateOnly: true** and validDuration = 0 the policy takes it as NEVER expire (which is what you saw).  

(2) is not something you can do via WebUI. (1) is the default WebUI behaviour and it is consistent with the CLI with similar parameters.
```
buildDefinitionId: 15
queueOnSourceUpdateOnly: false
manualQueueOnly: false
displayName: "1"
validDuration: 0
```

Can you please check this and confirm if this is still an issue for you?

**Comment by atbagga** [comment]
Closing the issue since I found it to be consistent in behaviour with the UI. 

@pietergheysens Please check if the above resolves your issue. Let me know if you still find some inconsistency.
