### ISSUE TITLE
`az devops wiki list` returns `request failed: Operation returned a 302 status code`

### ISSUE THREAD

**Issue by wibjorn** [Azure/azure-devops-cli-extension#924]
Hello, trying to automate some things related to a projects wiki. I've tried the following in the Cloud Shell, but keep getting the following back:

```
request failed: Operation returned a 302 code.
```

Commands run:

```
az devops wiki list --project <project-id-hash> --organization <URL to organization>
```
AND

```
az devops wiki list --project <name-of-project> --organization <URL to organization>
```

Neither seem to be returning anything, although the project/org definitely already contain wikis.

**Comment by ishitam8** [comment]
Hi @wibjorn ,

The above command won't return any results if there are no wikis present in that particular project.

To get the wikis at organization level, please use scope parameter
`az devops wiki list --organization <URL to organization> --scope organization`

If there is a project or code wiki already there in the project, then the command you executed is expected to return some results. 
In that case, could you please run the command again with '--debug' switch and share the logs?

**Comment by wibjorn** [comment]
Ah I see, yes, I should have been targeting only the org. I appreciate the help!
