### ISSUE TITLE
TF400497: The backlog iteration path that you specified is no longer valid.

### ISSUE THREAD

**Issue by DominikErnst** [Azure/azure-devops-cli-extension#926]
Hello,

how can I change the configuration / backlog iteration path?

Thx
Dominik

**Comment by ishitam8** [comment]
You can use  `az boards iteration team set-backlog-iteration --id<ITERATION_IDENTIFIER> --team <YOUR_TEAM>` to set backlog iteration for that team

**Comment by ishitam8** [comment]
I am hoping that above comment resolved your query. Hence, closing this issue, please feel free to reopen or raise a new one if you are facing any more issues.
