### ISSUE TITLE
[Bug]Getting a 405 on user remove call

### ISSUE THREAD

**Issue by brandongodby78** [Azure/azure-devops-cli-extension#928]
Using the az devops user remove command and the api call is getting a 405 with the error message that the resource does not support the DELETE method, although all of the documentation states it does. I will say the URL in my call is slightly different than the one in the API documentation.

I am using azure-devops version 0.16.0 

My command is formated as such: 
az devops user remove --user {redacted} --org "https://dev.azure.com/{redacted}/" --yes

![image](https://user-images.githubusercontent.com/20305285/71289320-e0835480-233a-11ea-8107-8983c335fefd.png)

**Comment by ishitam8** [comment]
Hi @brandongodby78 ,

What are you passing in argument --user?
It should be GUID or user Email ID.
I am guessing you are passing descriptor instead.

You can fetch the user GUID from `user list` command and pass that as --user, and it should work fine.

**Comment by brandongodby78** [comment]
Thank you for the advise @ishitam8. That did resolve my issue and it is working fine now, I will close this bug.
