### ISSUE TITLE
vsts work item create: ability to link related work items

### ISSUE THREAD

**Issue by jdanyow** [Azure/azure-devops-cli-extension#93]
Something like this would be super useful for our team:

```shell
vsts work item create ...required args... --parent xxxxxxxxxx
vsts work item create ...required args... --related xxxxxxxxxx
```

cc @adkinn

**Comment by leeberg** [comment]
This is my #1 top request - I am using VSTS CLI to clone projects from a master template project... but without the ability to set parent / related I am left with tons of "un-parented"  tasks and PBIs with no child tasks

**Comment by peteg18** [comment]
Very important for us as well!

**Comment by vbossica** [comment]
@jdanyow @leeberg @peteg18 Please have a look at #125 to see if it would fit your needs.

**Comment by jdanyow** [comment]
@vbossica looks good, much appreciated. Any ETA on a release?

**Comment by vbossica** [comment]
@jdanyow @tedchamb knows all the details about release ETA (I'm not part of the VSTS team and don't know their release cycle)

**Comment by VelinGeorgiev** [comment]
Its been 8 months since the pull request is being submitted. @tedchamb, any news on that?

**Comment by tedchamb** [comment]
@VelinGeorgiev, all I can say is that there is going to be a large round of investment in the cli coming soon.  These PRs are on the list.

**Comment by VelinGeorgiev** [comment]
Thanks for the update @tedchamb! Looking forward for that new update.

**Comment by gauravsaralMs** [comment]
I am proposing we start with 3 commands
`az boards work-item relation add`
`az boards work-item relation remove`
`az boards work-item relation-type list`

this should solve most of the customer scenarions
also in 
`az boards work-item show` we should be getting all the fields (including relations)

Using `az boards work-item relation-type list` users can list the types of relations supported in the Org
like https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20relation%20types/list?view=azure-devops-rest-5.0

then they can use oppositeEndReferenceName from this command to 
 `az boards work-item relation add`
`az boards work-item relation remove`

which will look something like this 
`az boards work-item relation add --id 4 --relation System.LinkTypes.Hierarchy-Forward=1,2,3`

cc: @geverghe  @snankani  @ishitam8

**Comment by geverghe** [comment]
FYI - @jdanyow , @leeberg , @peteg18 , @vbossica , @VelinGeorgiev

**Comment by jboulter11** [comment]
Will this PR include `--parent` on `create` or will that come in a follow-up?  Excited to see this being worked on! :)

**Comment by gauravsaralMs** [comment]
> Will this PR include `--parent` on `create` or will that come in a follow-up? Excited to see this being worked on! :)

at least not as part of the first cut, we will see how much popular this scenario is before implementing that.
Although this is still be achievable in 2 steps, i.e. first create and then link

**Comment by gauravsaralMs** [comment]
This will be available in next release, planned for something late this week or next week.
Closing this Issue as ability to link work items is added.

In case some other feature request/ enhancement is needed. Please raise a different issue.
