### ISSUE TITLE
Error to query Release Definition Name

### ISSUE THREAD

**Issue by diego7marques** [Azure/azure-devops-cli-extension#935]
## Describe the bug

**Command Name**
`az pipelines release list
Extension Name: azure-devops. Version: 0.16.0.`

**Errors:**
```
'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 615, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_FILTER_RESULT, event_data=event_data)
python3.6/site-packages/knack/cli.py, ln 162, in raise_event
    func(self, **kwargs)
...
python3.6/site-packages/jmespath/functions.py, ln 81, in call_function
    return function(self, *resolved_args)
python3.6/site-packages/jmespath/functions.py, ln 215, in _func_contains
    return search in subject
TypeError: 'in <string>' requires string as left operand, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az pipelines release list --query {} -o {} --top {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

Extensions:
azure-devops 0.16.0

```

**Comment by ishitam8** [comment]
@diego7marques ,

Can you share the complete command with debug logs [add --debug switch to your command]?
Please make sure to share your jmespath query.

**Comment by diego7marques** [comment]
@ishitam8,
I already found the problem. My command are with incorrect marks ("") for my context.
Thank you for your attention.
