### ISSUE TITLE
[Issue] How to offboard a team from Azure DevOps?

### ISSUE THREAD

**Issue by irwins** [Azure/azure-devops-cli-extension#942]
**Issue**
The on-boarding process of a team in Azure DevOps has been described. There are sample scripts on how you can automate this process, but how would you go about successfully off-boarding a team?

I'm curious as to what needs to be considered...

**Comment by geverghe** [comment]
Hey @irwins - thank you for the question and request. As I had mentioned offline, this process varies from team to team and my assumption is that there would be more divergence in this process than on-boarding. To start off with, is there an off-boarding process that you have today in your organization for Azure DevOps?

**Comment by irwins** [comment]
Hi @geverghe , Currently we're in the process of defining this. Part of the the on-boarding is setting up a DevOps project for the team with default specs. Once the team becomes obsolete, we need to clean up any project not in use... Is there away to soft-delete so to speak? Or have the ability to restore if necessary? (You never know)

I see now why yaml files can help with your build and release... 😉

**Comment by geverghe** [comment]
Ah I see. Here is the reference to [Delete project](https://docs.microsoft.com/azure/devops/organizations/projects/delete-project?view=azure-devops). As mentioned, a deleted project can be recovered in 28 days.  Including the exact text for clarification:

>Projects are permanently deleted if not restored within 28 days. For more information on restoring projects, see [Restore a project](https://docs.microsoft.com/azure/devops/organizations/projects/restore-project?view=azure-devops) . If you want to access project data while the project is deleted (without [restoring](https://docs.microsoft.com/azure/devops/organizations/projects/restore-project?view=azure-devops) it) you should [save project data](https://docs.microsoft.com/azure/devops/organizations/projects/save-project-data?view=azure-devops).

Therefore, you could use `az devops project delete` for your scenario.

Hope the above clarification is helpful. I am closing this ticket. Feel free to reopen in case you feel there is still something missing from the CLI front.
