### ISSUE TITLE
[Bug] az devops dont use logged in user to access https://dev.azure.com/

### ISSUE THREAD

**Issue by HenrikSommer-eng** [Azure/azure-devops-cli-extension#943]
**Describe the bug**
$organizatio = "your organization"
az devops project list --org --org https://dev.azure.com/$organization

Does not use current logged in user to access https://dev.azure.com/

**To Reproduce**
Azure Cli Version: 2.0.80
Azure-Devops extension version: 0.17.0

1. ps> az login --allow-no-subscriptions 
   **[User 1]**
2. close powershell console
3. ps> az login --allow-no-subscriptions 
  **[User 2]**
4. ps> $organizatio = "your organization"
az devops project list --org --org https://dev.azure.com/$organization

**Expected behavior**
It list the projects that [User 2] have access to

**Debug logs**
AzureCloud
trying to get token (temp) for tenant [guid] and user **[User 1]**
attempting to read file C:\Users\[username]\.azure\accessTokens.json as utf-8-sig

**Additional context**
The problem can be fixed by deleting C:\Users\[username]\.azure\accessTokens.json

**Comment by HenrikSommer-eng** [comment]
Did i post this the right place?

**Comment by atbagga** [comment]
Yes, this is the right place.

Did you run az devops login command earlier with the credentials of User1 in your case?

You can confirm this by running the command in debug mode i.e. with --debug flag and look for PAT is present which can be used against this instance.

![image](https://user-images.githubusercontent.com/11888714/73735388-33875e80-4765-11ea-8b24-45d9b31d4f05.png)

If yes, then logout using ```az devops logout``` command and run the command again this time the credentials should be az login credentials (NOT az devops login) and you should get desired output of projects which user2 has access to. 

Let me know if these steps help.

**Comment by HenrikSommer-eng** [comment]
I close this for now.
Since I can't reproduce it any more.
