### ISSUE TITLE
[Bug] az devops invoke doesn't support preview API versions

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-devops-cli-extension#946]
**Describe the bug**
I was trying to discover feed ids for our projects (since the feed ids I have to use for yaml pipelines aren't easily discoverable) using the CLI, but it doesn't support the preview API version I need: GET https://feeds.dev.azure.com/{organization}/{project}/_apis/packaging/feeds?api-version=5.1-preview.1

**To Reproduce**
Azure Cli Version: 2.0.76
Azure-Devops extension version: 0.17.0

Try to invoke a preview API, for example:
```
az devops invoke --organization "https://feeds.dev.azure.com/{organization}/{project}" --area packaging --resource feeds --api-version "5.1-preview.1"
```
View the output:
```
could not convert string to float: '5.1.1'
```

**Additional context**
The invoke command appears to be trying to convert the `api-version` into a float, even though it should just be left as a string.

Also, the invoke command also appears to be missing several URL parameters from the [documented](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1) form: `VERB https://{instance}[/{team-project}]/_apis[/{area}]/{resource}?api-version={version}`. For example, `team-project` is necessary now for packaging, and I'm not sure if `feeds.` should be part of the `{instance}` or not. It would also be nice if I could just provide a full API url and have `az devops invoke` provide authentication for that url.

**Comment by gauravsaralMs** [comment]
> It would also be nice if I could just provide a full API url and have az devops invoke provide authentication for that url.

you can explore  `az rest` command
example: 
```cmd
az rest -m get -u https://dev.azure.com/gsaralprivate/_apis/projects?api-version=5.1-preview.1 --resource 499b84ac-1321-427f-aa17-267ca6975798 -o json
```
--resource 499b84ac-1321-427f-aa17-267ca6975798 is a bit weird so adding info: </br>
 this GUID is the resource representation of ADO

**Comment by ishitam8** [comment]
I hope Gaurav's comment has resolved your issue. If not, please feel free to re-open the bug.

**Comment by Happycoil** [comment]
I don't really know python, but the problem seems fairly obvious. If you feed "6.0-preview-1" into this function it'll try to turn the string `6.0.1` into a float, which is not possible.

https://github.com/Azure/azure-devops-cli-extension/blob/2bd72a1d76cc00a84b348f573e9f8e14dfb42c5b/azure-devops/azext_devops/dev/team/invoke.py#L135-L138

The reason for converting the api version to a float appears to be to make the following comparison logic work:
https://github.com/Azure/azure-devops-cli-extension/blob/2bd72a1d76cc00a84b348f573e9f8e14dfb42c5b/azure-devops/azext_devops/dev/team/invoke.py#L91

**Comment by Happycoil** [comment]
Monkey patching my local installation with a trivial fix like following resolves the issue, so that tends to confirm my suspicions.
```python
def apiVersionToFloat(apiVersion):
    apiVersion = apiVersion.split('-preview')

    return float(apiVersion[0])
```

**Comment by jvdenning-et** [comment]
Why was this bug closed? It is not clear at all how to invoke REST API methods that in preview (given there is perpetually a preview version which has vital additions/enhancements).

**Comment by PiotrSkiba** [comment]
Issue is not solved. I am facing the same issue:

ERROR: could not convert string to float: '6.0.4'

Calling: https://dev.azure.com/{orgName}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4

**Comment by PiotrSkiba** [comment]
Issue is not solved. I am facing the same issue:

ERROR: could not convert string to float: '6.0.4'

Calling: https://dev.azure.com/{orgName}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4

**Comment by PiotrSkiba** [comment]
Issue is not solved. I am facing the same issue:

`ERROR: could not convert string to float: '6.0.4'`

Calling: https://dev.azure.com/{orgName}/_apis/serviceendpoint/endpoints?api-version=6.0-preview.4

**Comment by christofer-ja** [comment]
Please consider re-opening this issue as the bug is still present with azure-cli 2.37.0 & azure-devops 0.25.0

I've also reported this at Visual Studio Feedback: https://developercommunity.visualstudio.com/t/az-devops-invoke-doesnt-support-preview/10077588?space=21&entry=problem&q=devops+invoke

**Comment by cveld** [comment]
Please reopen

**Comment by walliski** [comment]
Azure Cli 2.65.0
azure-devops 1.0.1

And this as a reproduction step. This bug is very much still valid: `az devops invoke --api-version '7.2-preview.1'`

**Comment by DenisBalan** [comment]
same here! any upds?

```
(work_agn) denis@denis-Virtual-Machine:~/work_agn/repos_agn$ az devops invoke  \
--area Contribution \
--resource HierarchyQuery   \
--route-parameters project=GUID   \
--http-method POST   \
--api-version 5.0-preview.1   \
--accept-media-type "application/json;api-version=5.0-review.1;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true"   \
--media-type "application/json"   \
--org "https://dev.azure.com/MY_ORG"   \
--query-parameters "api-version=5.0-preview.1"   \
--in-file az-invoke-approve.json 

could not convert string to float: '5.0.1'
```
