### ISSUE TITLE
[Bug] az devops configure --defaults organization  URL Parsing error if Orgname contains %20

### ISSUE THREAD

**Issue by MrDomLeidos** [Azure/azure-devops-cli-extension#947]
I'm trying to configure :

az devops configure --defaults organization=https://dev.azure.com/sfa-gov-uk/My%20Org/
and it comes back with : 

invalid interpolation syntax in 'https://dev.azure.com/sfa-gov-uk/My%20Org/' at position 38

I am assuming it is the %20 escaping that is causing the problem, I can't change the name of the organisation as it's out of my control and used by 100's of other projects within the organisation.

Running with the debug switch I get a little bit more info about the error but not much 

handling value error
cli.azure.cli.core.util : invalid interpolation syntax in 'https://dev.azure.com/My%20Org' at posi
tion 38
invalid interpolation syntax in 'https://dev.azure.com/sfa-gov-uk/My%20Org' at position 38

I've tried removing the %20 and using spaces and wrapping within double & single quotes but neither work, it doesn't error but it doesn't set the organisation either.

Version numbers from : az --version

azure-cli                         2.0.81
command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

**Comment by atbagga** [comment]
Organization names do not have spaces in them hence no %20 should be there.

In the sample URL you provided the **my%20org**  part is the project name which you do not need to put in the organization url for setting default. 

If your url is something like this - ```https://dev.azure.com/sfa-gov-uk/My%20Org/```

Your command to setup defaults will look like this -
```
az devops configure --defaults organization=https://dev.azure.com/sfa-gov-uk project="my org"
```

Give it a try and let me know if you still have issues.

**Comment by atbagga** [comment]
@MrDomLeidos Please reopen if you still have issue with this.
