### ISSUE TITLE
[Bug] Starting in 0.13.0, terminal hangs when redirecting output

### ISSUE THREAD

**Issue by ssrobins** [Azure/azure-devops-cli-extension#948]
Install the latest version of the Azure DevOps extension:
`az extension add --name azure-devops`

Open Windows PowerShell
(I'm using 5.1.17763.771, which came with Windows 10)

Run the following command:
`$test = az pipelines pool list --organization https://XXXXXXXX`
Where `https://XXXXXXXX` is a valid Azure DevOps organization URL

I expect the terminal to return and the $test variable to be populated with the command output. Instead, the terminal hangs indefinitely until I type CTRL+C.

Now remove the extension:
`az extension remove --name azure-devops`

Install the 0.12.0 version:
`az extension add --source https://github.com/Azure/azure-devops-cli-extension/releases/download/20190805.1/azure_devops-0.12.0-py2.py3-none-any.whl`

Run the command again:
`$test = az pipelines pool list --organization https://XXXXXXXX`

It works as expected.

My current workaround is to downgrade to 0.12.0 so that I am able to use automate pipeline workflows with PowerShell.

az --version output:
```
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Steve\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.
```

**Comment by atbagga** [comment]
Not reproducible for me here.. though I see an issue with colors which is already filed on azure/knack  repo and I know is being worked upon. 

Will try to see through the debug logs in the other issue and see if I can repro.. 

@ssrobins The color issue does give an impression that it is hung but it is not. So please double check at your end it is not the issue. 

![CommandRun](https://user-images.githubusercontent.com/11888714/74425863-64107c00-4e7a-11ea-83a7-3a381cf75796.gif)

**Comment by ishitam8** [comment]
Closing this. Please feel free to re-open the bug if you are still facing this issue.
