### ISSUE TITLE
[Bug] Unable to disable telemetry

### ISSUE THREAD

**Issue by aodj** [Azure/azure-devops-cli-extension#950]
**Describe the bug**
It's not possible to disable the telemetry collection within the azure-devops extension for two separate reasons:
* When setting the configuration using `az configure -d collect_telemetry=...` the value is saved under the `[defaults]` heading in the azure-cli config file, which isn't detected by azure-devops since it's only reading the `[core]` section: [relevant link](https://github.com/Azure/azure-devops-cli-extension/blob/master/azure-devops/azext_devops/dev/common/telemetry.py#L68-L69)
* Secondly, the [documentation](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-file) around the `az configure` command states that
 > Booleans are case-insensitive, and are represented by the following values.
 > * True: 1, yes, true, on
 > * False: 0, no, false, off

which means that setting `collect_telemetry=false` is the same as setting `collect_telemetry=no`. However, the code in azure-devops does an equivalence check against `no` rather than using the `getboolean()` method that comes with the Python ConfigParser module for these situations. [relevant link](https://github.com/Azure/azure-devops-cli-extension/blob/master/azure-devops/azext_devops/dev/common/telemetry.py#L70)

**To Reproduce**
```bash
$ az --version
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location '/usr/bin/python3'
Extensions directory '/home/ansible/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
```

1. Disable the `collect_telemetry` flag in azure-cli with `az configure -d collect_telemetry=false`
2. Run an azure-devops specific command, with the `--verbose` and `--debug` flags set f.ex: `az pipelines build list -o table --verbose --debug`
3. Note the logged output: `Azure devops telemetry enabled.`
4. Reconfigure the azure-cli with `az configure -d collect_telemetry=no`
5. Rerun the `az pipelines ...` command, noting the logged output still contains `Azure devops telemetry enabled.`
6. Edit the Azure config file by hand, moving the `collect_telemetry = no` line from the `[defaults]` section to the `[core]` section
7. Rerun the `az pipelines ...` command, noting that that logs now record `Azure devops telemetry disabled.`
8. Edit the Azure config file by hand once more, changing the value of `collect_telemetry = no` to `collect_telemetry = false`. In the Python ConfigParser syntax these are equivalent.
9. Rerun the `az pipelines ...` command, noting that once again, the logged output contains `Azure devops telemetry enabled.`

**Expected behavior**
All telemetry sending to be fully disabled.

**Additional context**
The `az devops configure` command doesn't allow you to specify any options other than `organization` and `project` so it's not possible to set this value using the azure-devops cli. As such the emphasis is on using `az configure` to set this value. When you do, the primary azure-cli respects the flag, however azure-devops does not.

azure-devops only respects the flag when it's a) added into the `[core]` section, which can't be done from the command line, and furthermore, only respects one of the three valid negative options (ie: only respects `no` from the valid `no`, `false`, and `0` options).

**Comment by atbagga** [comment]
Note that the current code handles the core section which is what is set if you use ```az configure``` command interactively to set the telemetry. 

As the bug states, the check should honor all different ways the telemetry setting can be updated in AzureCLI.

**Comment by xavi0ne** [comment]
what is the az command to validate telemetry is disabled?

**Comment by ZenoArrow** [comment]
@xavi0ne If you run "az config get" it should list all of the configuration values you've set.
