### ISSUE TITLE
Please name git tags after the version as well

### ISSUE THREAD

**Issue by bluca** [Azure/azure-devops-cli-extension#956]
At the moment annotated git tags are named after the release date, rather than the version. This makes life for packagers harder, as there is a mismatch, and many automated tools fail. Eg: I cannot use the tag for the version when packaging in Debian as reverse dependencies will reference the actual version. But not using the actual git tag means automation to watch for new releases and import them does not work and has to be adjusted manually every time, which is a considerable waste of time.

Please consider tagging releases with the version (it can be an additional tag, doesn't have to be either/or).

**Comment by ishitam8** [comment]
Hi @bluca ,

You can create git tags by using the `az repos ref` management commands.
Does this work for you ?

Thanks

**Comment by bluca** [comment]
Hi,

I meant on this repository, as part of the release process of azure-devops-cli-extension itself. I uploaded this to Debian and Ubuntu, and it would make my life a lot easier maintaining it going forward.

**Comment by ishitam8** [comment]
Oh, got it.
Will make sure next releases are tagged as versions and not auto-generated dates [since only one tag is allowed.]

Thanks for the feedback :)

**Comment by bluca** [comment]
Thank you!

**Comment by bluca** [comment]
@ishitam8 the tag for the latest 0.18 release still doesn't match the version number: https://github.com/Azure/azure-devops-cli-extension/tree/20200401.4

**Comment by bluca** [comment]
This is till an issue after all this time - you call the release `Azure DevOps CLI extension for Azure CLI 0.24.0` but the git tag is https://github.com/Azure/azure-devops-cli-extension/tree/20220310.1
