### ISSUE TITLE
[Feature Request]AZ Repos Create with readme Feature request

### ISSUE THREAD

**Issue by ishitam8** [Azure/azure-devops-cli-extension#964]
Reference issue [here](https://github.com/Azure/azure-cli/issues/12165)

AZ Repos Create Feature request

I cannot create repos with an initial readme, when I use az repos create command.
An optional flag to create the repo with a README, would be really helpful. The command after running should also return the commit-id on the command line.
Please add this functionality.
The main point of having this is cloning this repo with a README, and not totally empty. In other words, creating a repo with atleast one commit on master.

**Comment by ishitam8** [comment]
Hi @ap-bansal ,

Apologies for the late reply.
Currently this feature is not supported in the azure-devops-cli, since there are no separate cmds to add/commit a file.
We rely on your git commands for this.

You can still combine the 'az repos create' command and git add/commit commands and automate your functionality.
Will that work for you ?

If not, can you please share your exact use-case?

**Comment by ap-bansal** [comment]
Hi @ishitam8, 
I have been using _az repos create_ and _git add/commit_ till now for automation. AZ Import doesn't work for private repos.
My actual need is to have a commit-id (SHA) when the repo is first made. Is there any way you can incorporate this in the AZ CLI codebase? 
Thanks,
Apar Bansal

**Comment by ishitam8** [comment]
Hi @ap-bansal ,
 
Please help me to understand your ue-case.
Do you already have a private repo (with required README or initial commits) and you want to import this repo to the newly created one?

**If yes, you can achieve this via az repos create and az repos import create cmds**
`az repos create -n <NEW_REPO_NAME>`

`az repos import create --git-url <URL_OF_REPO_TO_BE_IMPORTED> -r <NEW_REPO_NAME> --requires-authorization --user-name <USER_NAME>`

You will be asked for PAT.

Please let me know if this works for you.

Also , private repo import was added later, which is not reflected in help text of `az repos import create`. I will fix the same. Thanks for bringing that to our attention.

**Comment by ap-bansal** [comment]
Thanks Ishita. I'll give it a try.

**Comment by ishitam8** [comment]
Fixed in #978 . It will be available in next release.
