### ISSUE TITLE
[Feature Request] TSV output format with same columns as Table

### ISSUE THREAD

**Issue by SaqibS** [Azure/azure-devops-cli-extension#967]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I cannot create a project..

I wish to output work items into Excel. This would be trivial by using `--output tsv`, but this format gives me columns such as ID, None, 3, URL.

What I want, is the columsn given by `--output table`, so what I end up doing is manually replacing spaces with tabs and getting rid of the headers. But the other problem with `--output table` is that it truncates fields.

**Describe the solution you'd like**
e.g. If you want a new command to be added, what would it do?

A new output format (since changing TSV would be a breaking change, I guess) which outputs the fields I select, but in TSV format.

So in the below command:

```
az boards query --wiql "select system.id, system.title, system.assignedto, system.state from workitems" --output tsv
```

Would give me multiple rows, with each row containing ID, Title, Assigned To, State, separated by tabs. Today it gives ID, None, 3, URL.

**Additional context**

**Comment by ishitam8** [comment]
Hi @SaqibS ,

This is the limitation from az-cli for tsv format.
As stated in this [az-cli documentation](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#tsv-output-format) , there is no special handling for tsv format. Also ,  it can't output the nested entries.

You might want to pass the json results to additional scripts to get the output in your required format.

**Comment by ishitam8** [comment]
Hi @SaqibS ,

I hope you were able to get the results with some additional scripts.
If you are still facing issue related to output format, you can create an issue in [Azure CLI repo](https://github.com/Azure/azure-cli) 
I am closing this as of now.
