### ISSUE TITLE
[Feature Request] artifacts download should support any version type

### ISSUE THREAD

**Issue by jchauncey** [Azure/azure-devops-cli-extension#974]
**Is your feature request related to a problem? Please describe.**
I can publish an artifacts with any version string but using the CLI i can only fetch those that conform to semver 2.0. 

**Describe the solution you'd like**
I would like the ability to download any artifact that matches a given version string.

`az artifacts universal download --organization https://foo.visualstudio.com/ --feed myFeed --version 2020.01.01`

**Comment by magleaso** [comment]
Can you give an example of a version that you can publish but not fetch and provide a screenshot of that version in the UI?

**Comment by jchauncey** [comment]
![Screen Shot 2020-03-27 at 1 52 18 PM](https://user-images.githubusercontent.com/430360/77785218-41a17f00-7032-11ea-815e-30cc28c32d6c.jpg)

This is published by the Azure CNI team for their signed builds. I was trying to fetch it usign the cli which is a little easier to do than the other options.

**Comment by magleaso** [comment]
Sorry for the confusion. Universal here does not refer to a client for downloading any type of package, it refers specifically to downloading a single protocol known as Universal Packages. In order to install a NuGet package, you will need to use a client that supports NuGet. I understand this naming convention is confusing

**Comment by jchauncey** [comment]
So when Im looking at an artifact like hte one above and I say connect to the feed it gives me several options. One of those is nuget but there are others like universal packaging, python, npm, etc... Are you saying that none of those would work and the only way to interact with that feed is through nuget?

**Comment by magleaso** [comment]
Each of those refers how to download a different type of package. A feed can contain packages from any of those protocols. In this instance, you are trying to download a NuGet package, so you need a NuGet client.

**Comment by jchauncey** [comment]
ah k. That could definitely be made more apparent on those pages. Thanks again.
