### ISSUE TITLE
[Bug] az pipelines run not working with git tag

### ISSUE THREAD

**Issue by abergie** [Azure/azure-devops-cli-extension#988]
**Describe the bug**
az pipelines run not working with git tag

**To Reproduce**
Azure Cli Version: 
azure-cli (2.3.1)

Azure-Devops extension version: 
azure-devops (0.18.0)

az pipelines run --id `<id>` --branch refs/tags/1.0.0

**Expected behavior**
pipeline with `<id>` is executed using refs/tags/1.0.0

**Actual behavior**
Error: The pipeline is not valid. Could not get the latest source version for repository `<repo-name>` hosted on Azure Repos using ref refs/heads/refs/tags/1.0.0

**Comment by abergie** [comment]
It seems this commit is where the behavior has been changed. https://github.com/Azure/azure-devops-cli-extension/commit/9076bfbe5bd1511c2f8ed1f85e274a0db51afe7b#diff-46be2ad4e98ca131a0f8cb2ba1c09e96

**Comment by abergie** [comment]
Opened PR #989

**Comment by abergie** [comment]
PR #989 Merged

**Comment by abergie** [comment]
@narula0781 @ashishonce @romil07 Was wondering when the next release is scheduled? Would like to be able to pull in the fix from PR #989 Thanks!

**Comment by jayakumarj85** [comment]
Is this issue fixed. I am still getting the same error while trying to select a tag before running the pipeline?

**Comment by mahmoudajawad** [comment]
I need to use a disposable machine for using azure-cli and every time I need to manually apply this patch. Is this not going to make it into the production release of azure-cli?
