### ISSUE TITLE
[Bug] Incorrect Extension Information

### ISSUE THREAD

**Issue by reynoldsbd** [Azure/azure-devops-cli-extension#996]
## Description

The `az version` and `az extension show -n azure-devops` commands show incorrect information about this extension.

## To Reproduce

Azure Cli Version: 2.5.0
Azure-Devops extension version: 0.18.0 (I think ??)

1. Run `az version` or `az extension show -n azure-devops`

### Actual Behavior

`az version` produces the following output. Note the incorrect version number (1.25.8) for azure-devops.

```
{
  "azure-cli": "2.5.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-devops": "1.25.8"
  }
}
```

`az extension show -n azure-devops` is similarly incorrect. It also offers some hints as to what might be causing this issue. Note that the "metadata" property appears to contain information about one of the extension's dependencies (urllib) as opposed to information about azure-devops itself.

```
{
  "extensionType": "whl",
  "metadata": {
    "author": "Andrey Petrov",
    "author_email": "andrey.petrov@shazow.net",
    "azext.minCliCoreVersion": "2.0.69",
    "classifiers": [
      "Environment :: Web Environment",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Operating System :: OS Independent",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7",
      "Programming Language :: Python :: 3.8",
      "Programming Language :: Python :: 3.9",
      "Programming Language :: Python :: Implementation :: CPython",
      "Programming Language :: Python :: Implementation :: PyPy",
      "Topic :: Internet :: WWW/HTTP",
      "Topic :: Software Development :: Libraries"
    ],
    "description": "<omitted for brevity>",
    "description_content_type": "text/markdown",
    "filename": "C:\\Users\\boreynol\\.azure\\cliextensions\\azure-devops\\urllib3-1.25.8.dist-info",
    "home_page": "https://urllib3.readthedocs.io/",
    "keywords": "urllib httplib threadsafe filepost http https ssl pooling",
    "license": "MIT",
    "maintainer": "Paul Ganssle",
    "maintainer_email": "dateutil@python.org",
    "metadata_version": "2.1",
    "name": "urllib3",
    "platforms": [
      "UNKNOWN"
    ],
    "project_urls": [
      "Documentation, https://urllib3.readthedocs.io/",
      "Code, https://github.com/urllib3/urllib3",
      "Issue tracker, https://github.com/urllib3/urllib3/issues"
    ],
    "provides_extras": [
      "brotli",
      "secure",
      "socks"
    ],
    "requires": [
      "six"
    ],
    "requires_dist": [
      "brotlipy (>=0.6.0) ; extra == 'brotli'",
      "pyOpenSSL (>=0.14) ; extra == 'secure'",
      "cryptography (>=1.3.4) ; extra == 'secure'",
      "idna (>=2.0.0) ; extra == 'secure'",
      "certifi ; extra == 'secure'",
      "ipaddress ; (python_version == \"2.7\") and extra == 'secure'",
      "PySocks (!=1.5.7,<2.0,>=1.5.6) ; extra == 'socks'"
    ],
    "requires_python": ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4",
    "summary": "HTTP library with thread-safe connection pooling, file post, and more.",
    "version": "1.25.8"
  },
  "name": "azure-devops",
  "version": "1.25.8"
}
```

### Expected behavior

Information relating to the azure-devops extension is correctly represented

## Additional Context

My team has some scripts that we use to help validate that developers have all the necessary dependencies installed before working with our repo. These scripts rely on accurate output from `az version` and `az extension show ...` in order to correctly diagnose incorrect or out-of-date developer environments.

**Comment by jkewley** [comment]
Seeing  this as well, also testing platform compliance scripts. My `az version` shows 
```
{
  "azure-cli": "2.5.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "application-insights": "0.1.7",
    "azure-devops": "1.25.9",
    "interactive": "0.1.9",
    "subscription": "0.1.3"
  }
}
```
I just updated my azure-devops extension on Wednesday, so this seems to have happened over the last couple of days. I see that the CLI version 2.5.1 was released today - perhaps related?

**Comment by reynoldsbd** [comment]
Indeed, the release notes for 2.5.1 mention something about loading the wrong metadata for extensions:

https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md

After upgrading to 2.5.1 the correct information is being displayed.

**Comment by jkewley** [comment]
@reynoldsbd can you please reopen this? This is still a bug with AZ versions less than 2.5.1, which makes it a breaking change for CLI versions prior to today's release.

**Comment by reynoldsbd** [comment]
It's not a breaking change, it's a bug, one which has now been fixed in a backwards-compatible patch release of the Azure CLI (2.5.1). Furthermore, since this is an issue with the CLI itself and not the DevOps extension, this repository is not the right place for this issue.

**Comment by jkewley** [comment]
Well it appears that we are seeing different things, which is interesting.

On Wednesday `az extension add --name azure-devops` installed 1.25.9
Without upgrading to 2.5.1 that extension still reports locally as 1.25.9 with `az version`

Today, for me, the CLI versions 2.2.0, 2.5.0, and 2.5.1 all report 0.18.0 as the available version for the azure-devops extension when running `az extension list-available`. Running `az extension add --name azure-devops` with 2.5.1 installs a version which reports locally as 0.18.0

I'm curious where you're seeing it work correctly

Something broke since Wednesday that makes existing client tooling behave differently. It's probably a CLI issue, but it's manifesting itself as a problem with trying to get the latest version of azure-devops. If you don't want to reopen this one I'll create a new one

**Comment by reynoldsbd** [comment]
You're assuming that `list-available` was impacted by this bug, but I see no evidence of that.

If upgrading your CLI to 2.5.1 fixed the bug, then I don't understand what reopening this issue or opening a new issue will accomplish, as the root cause has [already been fixed upstream](https://github.com/Azure/azure-cli/pull/13222). If you choose to do so anyway, I recommend opening the issue in [the main Azure CLI repo](https://github.com/Azure/azure-cli) rather than here to make sure it's visible to the right set of people.

**Comment by jkewley** [comment]
For future visitors - it looks like 1.25.8 and 1.25.9 were the bugged versions and 0.18.0 is the current one
